### ISSUE TITLE
TxPool Event naming 논의

### ISSUE THREAD

**Issue by hea9549** [DE-labtory/it-chain#157]
TxPool 에서 publish 하는 이벤트 목록(가칭)
- TxReadyToBlockEvent (1)
- TxSendToLeaderEvent (2)

(1) 자신이 리더 노드일 경우 모여있던 트랜잭션을 블록으로 만들 준비가 됬다는 이벤트를 보낸다
(2) 자신이 리더노드가 아닐경우 모여있던 트랜잭션을 리더노드에게 보낼 준비가 됬다는 이벤트를 보낸다

에대한 이벤트 네이밍 논의가필요합니다.

**Comment by hea9549** [comment]
@junbeomlee 왜 나는 라벨권한이없는가 ㅠㅗㅠ

**Comment by junbeomlee** [comment]
저의 추천은 
(1) BlockReadyEvent
(2) TransactionSendEvent

정도?

**Comment by hea9549** [comment]
(1)번은 Transaction이랑 관련없이 블록이 준비됬다 이런느낌이 들어서
트랜잭션이 (블록으로 만들) 준비가 됬다 이런느낌의 단어가 필요할거같은데
명사 + 동사 + Event로 하기엔 부족한데 흠...
TransactionReadyForBlockEvent 너무길어
어떡하지 다른 더 좋은거 없을까요?

(2)번은 좋아요!

**Comment by hea9549** [comment]
Consume Event 목록에서
CreateTxEvent
말고 추가로 RecieveTxEvent도 필요할거같은데 어떻게생각해요?
리더의 경우 다른 노드에게서부터 Tx를 받으니까 저 이벤트필요할듯

@junbeomlee

**Comment by hihiboss** [comment]
(1)번에 대해서  BlockPreparedEvent 로 의견 던져봅니당

@hea9549

**Comment by junbeomlee** [comment]
BlockPreparedEvent 찬성아니면 BlockProposalEvent

**Comment by junbeomlee** [comment]
TxReceivedEvent로해서 포맷을 맞추는게 좋을듯?

**Comment by hea9549** [comment]
Comsume Event
- TransactionCreateEvent
- TransactionReceiveEvent
- LeaderChangeEvent

Publish Event
- TransactionSendEvent
- BlockProposeEvent

로 마무리되었습니다
@junbeomlee  @hihiboss 
pull : #159
