### ISSUE TITLE
Genesis block from config

### ISSUE THREAD

**Issue by junbeomlee** [DE-labtory/it-chain#164]
genesis.conf로 부터 gensisblock 생성

**Comment by ttkmw** [comment]
@junbeomlee @byron1st 
CreateGenesisBlock을 Engine으로 옮기는 과정에서 질문이 있습니다.
1. 위그드라실은 it-chian-Engine 뿐 아니라 다른 사람이 만든 블록체인 엔진(예를 들어 A-chain-Engine, example-chain-engine 등)이 각자 커스텀한 블록을 저장할 수 있도록 하는 라이브러리가 맞나요?
2. 그렇다면 위그드라실의 default_block은 위그드라실에 잘 저장이 되는지 확인하기 위한 블록 예제인 것인데, it-chain-engine에서 새로운 블록 구조체를 만들어줘야 하는건가요?(예시: it-chain_block) 이렇게 되면 default_block을 만들기 위해 임포트했던 default_transaction도 엔진에서 다시 만들어줘야 할텐데, 그렇진 않을 것 같아서요...!

**Comment by junbeomlee** [comment]
구조체를 만들어도 되고 

```
type Default_block struct {
}

type block = Default_block
```

이런식으로 Custom type을 정의할때 같은 type이라고 지정한 후에 우리는 block을 사용하거나 할수도있을 것 같습니다.

**Comment by ttkmw** [comment]
넵 일단 같은 타입이라고 지정하는 방향으로 해보겠습니다~

**Comment by byron1st** [comment]
@junk-sound 
`DefaultBlock` 은 예제인 동시에 `it-chain-Engine` 에서 사용하는걸 최우선해서 만들었습니다. 만약 `it-chain-Engine` 에 특화된 추가 요구사항이 있으면 yggdrasill 에 이슈를 남겨주시거나 `DefaultBlock` 에 구현하셔도 됩니다. 사실 그래서 이름을 Default 대신 `ItChainBlock` 으로 할까도 고민했습니다 ㅎㅎ
