### ISSUE TITLE
grpc gateway 관련 이벤트

### ISSUE THREAD

**Issue by hea9549** [DE-labtory/it-chain#165]
grpc gateway 관련 이벤트 논의
#163  의

    이부분은 Network를 통해서 전송되는 부분인데 
    이부분을 공통포맷으로 정의하고 싶어서 Grpc-gate event보면 
    다른 피어로 전송하는 데이터는 모두 []string과 body []byte, protocol 로 되어있는데 
    여기서 leaderID와 body에는 transactions의 byte그리고 protocol에 
    TransactionSendEvent가 들어가야 되지 않을까 하는데 이부분은 얘기를 해봐야 할듯? 

을 제안하고있는것에대한 논의

**Comment by junbeomlee** [comment]
[]string 에 leaderID,  body에 transactions, protocol에  TransactionSendEvent가 들어가게 하려고 만든게 맞아용!! {보낼 사람들, 보낼 데이터, 어떤 데이터인지} 이렇게

**Comment by junbeomlee** [comment]
close할꼐요
