### ISSUE TITLE
cli 추가

### ISSUE THREAD

**Issue by junbeomlee** [DE-labtory/it-chain#174]
cli기반으로 it-chain engine을 컨트롤 할려고합니다.

ex) 
/it-chain peer start 
/it-chain icode deploy [url]

**Comment by byron1st** [comment]
다른 저장소에서 cli 관련해서 https://github.com/urfave/cli 이 라이브러리를 써봤는데, 직관적이고 상당히 괜찮더라구요.

**Comment by junbeomlee** [comment]
찾아보니 cobra와 cli 2파전 처럼 보입니다!! hyperledger는 cobra를 사용했네요!

2018년 5월 9일 (수) 오후 4:39, Hwi Ahn <notifications@github.com>님이 작성:
