### ISSUE TITLE
messaging topic naming convention제안 

### ISSUE THREAD

**Issue by junbeomlee** [DE-labtory/it-chain#177]
it-chain에서 사용하는 topic의 naming convention을 제안합니다.

it-chain에서 사용되는 event들은 크게 2개로 구분되는데 
1. 각 서비스가 관리하는 domain객체들의 변화 event
2. 다른 서비스에게 로직수행을 요청하는 event

입니다. 기존에 구현되는 방식은 위의 event들은 크게 구분하지 않았는데 그러다 보니 event들이 헷갈리고 명확하지 않은점이 있어서 아래 링크를 참고하여 새로 방법을 제안하려고합니다.

크게 3개로 구성되어있는데 {domain객체}.{event유형}.{action}이라고 볼 수 있을 것 같습니다. domain객체라고하면 user, connection 등이 될 것이고 event유형이라면 위에서 말한 2가지가 있는데 domain객체의 상태 변화 -> event, 로직 수행 요청 -> cmd가 될 것 입니다. action은 deleted, created나(domain객체의 상태변화의 경우)  delete,create(로직 수행 요청일경우)가 될 것 같습니다. 좀더 자세한 내용은 아래 링크를 보면 좋을 것 같습니다. 의견 주세요!!

아래 링크에서 **Exchange Per Object Type** 패턴을 참조했습니다.

[참고 링크] https://derickbailey.com/2015/09/02/rabbitmq-best-practices-for-designing-exchanges-queues-and-bindings/

**Comment by hea9549** [comment]
domain event의 경우 기존 사용하던거라 혼동이없는데
cmd의 경우 조금 햇갈릴 수 있는데
ex ) domain cmd create
      conn    cmd    create

이렇게되면 conn 도메인 생성 요청 이벤트 일텐데
그대로 읽으면 커넥션이 create를 하는것같아서 혹시 순서를
domain.action.event 로 가는건 어떨까요?
conn create cmd
conn deleted event
이런식으로요!

**Comment by junbeomlee** [comment]
오 훨씬 좋은듯 !
