### ISSUE TITLE
대략적인 인증 서비스에 대한 정리입니다.

### ISSUE THREAD

**Issue by ghost** [DE-labtory/it-chain#189]
Hyperledger를 참고하다보니 네이밍에 Hyperledger에서 사용하는 것들이 포함되어있을수 있습니다.
@junbeomlee 님께서 일단 Single Channel로 만들고 계신다하여 Multi Channel의 관점은 제외했습니다.

내용은 다 넣었지만 그림을 어떻게 정리할지 고민중(엉망)이라.. 일단 내용만 봐주세요..!
질문이나 코멘트 환영합니다 :)

**1. 개요도 입니다.**
![image](https://user-images.githubusercontent.com/32866399/40152991-9b07508e-59c2-11e8-82dc-f95667db3eb6.png)

* chain of trust는 보증 같은 개념입니다. Root CA가 신뢰기관이니 Root CA로 부터 인증서를 받은 주체, 인증서를 받은 주체로부터 인증서를 받은 주체...들을 모두 신뢰할 수 있다고 보는 것 입니다.

* 기본적으로 인증서는 X.509 표준 형태로 사용합니다.

* **<BC(Blockchain)에 영향을 줄 수 있는 주체들에게 모두 cert(인증서)를 할당합니다.>**

* ECert는 Enrollment Certificate의 약어로, 우리가 평소 사용하는 공인인증서 같이 신원을 증명하는데 사용됩니다. 더 자세히는 "이 인증서 내의 public key가 이 주체(인증서내 subject)의 소유가 맞다"라는 것을 인증해주는 것입니다. (비교적 오랜기간 사용됩니다.)

* TCert는 Transaction Certificate의 약어로, end-user의 프라이버시 보호를 위해 트랜잭션 생성 시 마다 사용되는 1회용 인증서입니다. 

1) BC참여멤버(org)들은 합의(physical 세계에서의 합의)하에 정한 신뢰기관 Root CA로부터 인증서를 발급받습니다.
(Root CA는 외부기관 혹은 참여멤버들이 만든 임시기관 등등 참여멤버들이 신뢰하는 기관이면 됩니다.)
(org는 기관일수도 있고 한명의 사람일수도있는 BC참여멤버입니다.)

2) 각 참여멤버들은 Root CA로부터의 인증서를 기반으로 참여멤버들에 소속된 다른멤버나 peer들에 인증서를 제공하는 CA로 활동합니다.

3) smart contract와 Client app을 개발하는 app 개발자들도 BC에 영향을 줄 수 있고, 그 app을 사용하는 end-user들도 마찬가지기에, 각각은 인증서를 발급받습니다.

4) 각 트랜잭션(Tx)에 대한 인증서 발급은 end-user의 프라이버시를 위해서 필요한 부분인데, 지속적으로 같은 서명키를 사용해서 트랜잭션에 서명하면 트랜잭션을 열람할 수 있는 입장에서는 추적이 가능하기 때문에 트랜잭션마다 다른 서명키를 사용하는 것 입니다. (optional한 부분이라 초기단계에서는 굳이 없어도 될 것으로 보입니다.)

**2. 예시로 end-user에 대한 ECert 발급 과정입니다.**

![image](https://user-images.githubusercontent.com/32866399/40153878-c12cb282-59c6-11e8-9606-717b11e3e639.png)

**3. 그래서 auth service가 제공해야할 것으로 보이는 기능들입니다.**

![image](https://user-images.githubusercontent.com/32866399/40153986-2d76b636-59c7-11e8-87b5-b1d0d1b1138a.png)

**그림에 밑줄친대로 서비스를 구현하되 각 멤버의 차상위 CA(Root CA로부터 인증서를 발급받은 CA)를 시작으로 각 인증서에 기재되있는 소속, 속성 등의 요소를 이용해서 서비스 내의 CA기능 활성화 여부를 결정합니다.**

Sign, Verify, keygen, keystore는 heimdall에 구현되어 있습니다. (서명키 암호화를 위한 암호화키생성, 암호화는 아직..)
Sign/Verify는 말그대로 서명과 서명을 검증하는 기능입니다.
keygen은 키 생성, keystore는 키 저장을 말합니다.

RA(Registartion Authority)
- ECert 발급에 필요한 등록 사용자명/패스워드(OTP) 관리

Enrollment CA
- BC 네트워크 참여 멤버들의 신원 증명을 위한 인증서 발급

Transaction CA
- end-user의 프라이버시 보호를 위한 일회용 인증서 발급

TLS CA
- 네트워크 참여 멤버간의 통신 채널 보안을 위한 인증서 발급
- TLS 인증서를 이용한 보안채널로 ECert를 발급받으면 사용하지 않을것으로 보입니다.

틀을 어느정도 만들었으니 잘못된 부분이 없다면 그림과 설명들 다시 한번 다듬은 후에 구현을 시작하려합니다.
혹시나 이해가 안되시거나 잘못되었다고 생각하시는 부분은 바로 말씀해주세요!
그림의 깔끔한 정리에 대한 조언도 환영합니다 :)

**Comment by byron1st** [comment]
CA 자체가 auth service 내로 들어오지는 않을 것 같습니다. Fabric의 경우도 블록체인인 Fabric과 Fabric CA는 완전히 구분된 프로젝트이고, Fabric의 peer/orderer 들은 누가 발급했건간에(Fabric CA도 포함) X.509 포멧에 맞는 인증서만 있으면 사용할수 있습니다.

`it-chain`도 우선은 X.509 인증서를 각 노드들이 모두 갖고 있다고 했을 때, 이 중 허가된 노드만 네트워크에 참여할 수 있도록 하는 노드 수준의 멤버쉽 관리에 대한 개발이 우선되고, 인증서를 발급하는 CA는 사이드 프로젝트로 `it-chain-Engine`과 별도로 진행될 수 있을 것 같습니다.

우리는 중앙 서버가 따로 없기 때문에, 허가된 노드 리스트라는걸 어떻게 표현하고(예를 들어, 인증서 리스트로 나타낼지, 노드 아이디로 나타낼지 등등), 이 리스트를 어떻게 서로서로 공유하며, 인증서를 이용해서 어떻게 허가된 노드임을 알 수 있을지 등이 중요 이슈일거 같네요.

**Comment by byron1st** [comment]
아, 혹시 마지막 그림의 auth service가 잇체인 내의 auth service가 아니라 Fabric CA처럼 별도 노드인가요?

**Comment by ghost** [comment]
@byron1st 
좋은 포인트에 대한 코멘트 감사합니다!
(제가 많이 헷갈려 고민했던 부분이기도 합니다!)

auth service 내의 CA는 모든 노드에 CA 권한이 있는 것이 아니라 chain of trust의 인증서 체계에 따라 CA기능에 대한 권한 부여를 할 수 있을 것으로 보여서 포함시켰습니다.

예를 들면, 말씀하신대로 임의의 신뢰할 수 있는 Root CA로부터 org1이 받은 인증서에서 subject 필드내에 
country(C)=KR
state(ST)=Seoul
Local(L)=GwangJin
organization(O)=org1
organizational unit(OU)=top
CN=myorg
와 같이 넣으면 이후에 org1이 인증서를 org1에 소속된 노드에 발행시 
OU필드에 div1, CN필드에 peer1과 같이 입력이 되겠지요.


O필드에 org1 OU필드에 top이라면 org1의 최상위(?)를 나타내고 이런 경우 노드의 부팅 시 msp에서 검사하여 root ca의 인증서와 root ca의 서명이 들어간 org1의 인증서를 확인하고 org1 노드에서는 CA의 기능을 On하고요.

이렇게 되면 org1에 소속된 노드의 인증서에는 모두 O 필드에 org1이라는 값이 있을것입니다.
정책적인것이지만 div단위까지만 CA권한을 부여한다면 OU가 top 혹은 div인 노드만 CA의 기능을 할 수 있는 것이지요.
그럼 자연스레 이들이 org1에 소속되고 Root CA로부터 받은 인증서로 org1은 다른 org2, org3 등에게 BC net에 참여하는 노드로서 인증을 할 수 있고요.
(Root CA는 BC net 초기설정에서 참여 멤버들이 정한다고 가정합니다.)
(이 가정을 위해 genesis 블록에 신뢰기관(root ca)에 대한 어느정도의 표시가 필요할 것 같습니다.)

그리고 Private Chain(Permissioned Chain)은 기본적으로 멤버로서 인정 및 신뢰받아야 참여할 수 있는 개념인데 X.509 포멧에 맞는 인증서만 있다면 누가 발급했건 상관이 없는 건 아닐것 같습니다..!(멀티채널로 구성한다면 조금 달라질 수 있겠지만 지금은 싱글채널로 구현중이라고 들었습니다.)

참고적으로 1) Fabric CA는 fabric MSP의 한 구현체라고 합니다. 그리고 2) org는 크게는 기업, 국가 같은 조직도 될수 있겠지만 작게는 그저 한 사람 정도의 규모가 될 수도 있을것으로 보입니다.

혹시 코멘트주신 부분에 대해 또 다른 코멘트나 의문점이 있으시다면 말씀해주시고 이 부분 외에도 코멘트 환영합니다 :)

그리고 readme에 등록하기 전에 부족한것으로 보이는 1) X.509 인증서 포멧의 구성요소, 2) chain of trust에 대한 설명,  3) 인증서 필드를 이용한 권한관리 방법 + hyperledger에서 사용하는 ABAC(속성기반권한관리) 방법도 추가해보겠습니다!

**Comment by junbeomlee** [comment]
넵 잘 정리해서 문서화하면 아주 좋은 내용이 될것 같습니다!! 대단 대단... 
아래 내용 추가한다음에 한번더 이부분에 대해서 얘기해보면 좋을 것 같습니다!! 추가되면 알려주세요!!
오프라인때 한번 발표해주시면...ㅎㅎ 이번주 주말에 해주세여...

**Comment by ghost** [comment]
자료를 준비하다보니.. 제가 잘못 생각했었던것 같습니다.. ㅠ 

@byron1st 님의 말씀대로 노드가 인증서를 가지고 있다는 가정이 auth service에 들어가야 할 것 같네요.


일단 노드 외적인 부분들에 대해 먼저 짚고 넘어가야할 것 같습니다.

0. BC net 초기 구성 시 genesis block이나 어딘가에 BC net 참가자들이 신뢰하는 Root CA들의 인증서가 포함되어야 할 것으로 보입니다.

1. '**허가된 노드**'라는 것은 이미 CA에서 노드의 BC net 참여 시 인증서를 발급할 때 해당 노드의 관리자(혹은 소유주)의 인증으로 증명이 될 것입니다. (말씀하신 노드 ID도 인증서내의 필드에 포함될 것입니다.)

2. private chain 특성 상... 앱, 사용자, (멤버)노드 등은 BC net 참여를 위해 초기 설정에서 기록한 Root CA(들)에서 뻗어나오는 trust chain의 일부 CA로부터 인증 단계를 거칩니다.  
예를 들면 이전의 예처럼 org1, org2 두 집단이 어떤 비즈니스를 위해 BC net을 사용하기로 했을 때, 초기 설정 시 두 집단이 공통으로 신뢰하는 하나 이상의 global root CA(들)로 부터 CA용 인증서를 받아 org1.div1과 같이 여러개의 하위 CA를 만들고 trust chain을 형성합니다.**(BC net node와는 관계가 없습니다.)**

3. 결과적으로 인증서의 공유는 그 인증서를 발급한 CA들에게 요청하고 동기화해야할 것 입니다. (trust chain 이용)


**이제 다시 auth service로 돌아오면,** 

1) CA 기능은 노드가 포함할 필요가 없고, CA는 BC net 외부(경계?)에서 신원확인/인증서 발급 등 기능을 포함하며 말씀하신대로 노드가 아닌 다른 개체로 존재해야할 것으로 보입니다. 

2) 노드에 포함되는 서비스인 auth service는 말씀하신 인증서 리스트 및 키 저장소(?)와 서명/검증의 기능을 포함해야 할 것입니다. 
여기서 인증서 리스트는 앞서 말씀드린것처럼 BC net에서 신뢰하는 CA들(노드가 BC net에 접속 시 인증서를 발급하는 CA들)로 부터 동기화를 하는 것이 일반적인 방법일 것 입니다.

사실 위에서 말씀드린 내용들이 거의 다 CA로 넘어가는 기능들이라, auth service에는 heimdall에 포함된 기능들을 묶어서 편하게 사용할 수 있게하면서 약간의 인증서 관련 기능들만 추가하면 될 것으로 보입니다. 

이 내용을 바탕으로 다시 그림을 그리려 하는데.. 혹시 또 다른 코멘트가 있다면 조언 부탁드립니다!
(추가로, 이전에 말씀드린 권한관리도 BC net 참여 노드들에게는 필요하지 않아 보입니다.)

@junbeomlee 
@byron1st

**Comment by junbeomlee** [comment]
@owljoa 
저도 어제 @byron1st 님께 물어봤는데 인증서같은 경우에 auth service에서 자동으로 제공해주는 것이 아니라 알아서 인증서를 위에서 말한 자식 부모 관계로 만들어서 배분해줘야 한다고 하네요. 인증서의 발급은 CA로 별도로 구분해 주는 것이 저도 맞다는 생각이 듭니다!! 노드는 검증으로!

궁금한게 TCert는 그러면 어떻게 처리되나요?!

**Comment by ghost** [comment]
@junbeomlee 
넵넵 그게 맞는 방법 같아요 :)
제가 public chain하고 자꾸 겹쳐서 이상한 생각을 하네요 ㅠ

TCert도 ECert 이용해서 TCert 발급하는 TCA에 요청하면 됩니다. 
'ECert를 이용'하는 부분에서 '키 유도'라는 개념이 들어가던데.. 이 부분은 공부를  좀 해야할 것 같아요.. 하하;

**Comment by ghost** [comment]
@junbeomlee 
readme 형식에 맞춰서 만들어보고 있습니다.

consume할 이벤트에는 인증서 리스트에 변경사항 (다른 노드 혹은 CA의 인증서가 폐기되었다던지..)들이 있을 것 같은데, 이 부분은 폐기된 인증서의 상위 CA와 동기화해야 할 것 이고요. 

**여기서 it-chain engine에 CA는 포함되지않는데 이벤트로 넣어도 되는건가요??**

그리고 일단 메시지라고는 적어두었는데 제가 의도한것은 네트워크 내에서 Blockchain에 직접 접근하는 메시지입니다.

**it-chain에서 트랜잭션 타입  이외에 blockchain에 접근하는 메시지가 있나요??**

그리고 다른 부분들도 잘 만든것인지 혹시 보완해야할 부분이 있다면 조언 부탁드립니다! :)

1. Auth service의 범위

- 노드의 초기화 시 노드 등록 절차 수행
- 노드 등록 시 생성한 키와 발급된 인증서의 저장 및 관리
- 등록 CA와 인증서 체인의 인증서 리스트 동기화 수행
- it-chain network내의 메시지 및 송신자 검증 수행
- 노드가 메시지 전송 시 서명 수행

2. Auth service가 다루는 핵심 데이터

- 노드의 송/수신 메시지
- 개인키, 인증서 리스트(?)

3. Auth service Consume event

- CertRevocationEvent(?)

4. Auth service Publish event

- MsgVerifiedEvent(?)
- MsgSignedEvent(?)

**Comment by byron1st** [comment]
@owljoa 
범위를 명확히 정리해주시니 이해가 아주 잘되어 좋네요^^
질문이 몇가지 있는데요, 1. Auth service의 범위에서,

> 노드의 초기화 시 노드 등록 절차 수행

이게 인증서를 갖고 다른 노드를 통해 부트스트래핑하는 것을 의미하는 것인가요?

> 등록 CA와 인증서 체인의 인증서 리스트 동기화 수행

여기서 "등록 CA"와 "인증서 체인"은 어떤걸 의미하는 것인가요? 위에서 말씀하신 "BC net에서 신뢰하는 CA들"을 의미하는 것인지요?

어느정도 정리가 되면, Auth 서비스의 시나리오를 시퀀스 다이어그램으로 표시해주는 것도 좋을 것 같습니다. ^^

**Comment by ghost** [comment]
@byron1st 
아하하 :) 칭찬 감사합니다. 

질문 답변 드리겠습니다.

1. 노드 등록
CA에 네트워크 멤버 org 소속의 네트워크 admin(관리자)들이 정상적으로 등록되어 있다는 가정을 했습니다.
노드 등록 절차는 원격 혹은 직접적으로 admin(관리자)이 인증과정을 거쳐서 CA에게 노드의 등록과 인증서를 요청하고 발급받는 과정입니다.

2.  BC net에서 신뢰하는 CA들은 네트워크 구성원들이 계약서나 genesis block이나 어디든 서로 인정할 수 있는 매체로 미리 지정을 해두는 것이고, 이들은 BC net 관점에서의 Root CA로 가정했습니다.
등록 CA는 해당 노드에게 인증서를 발급한 CA이고 사실 이 등록 CA도 인증서 체인에 포함이 될것입니다.
인증서 체인은 이전에 말씀드린 chain of trust를 생각하시면 그 최하단에 노드가 있을 것이고 최상단에는 root ca가 있을 것 입니다. root ca부터 최하단의 해당 노드까지 가는 경로의 ca들의 인증서를 의미합니다.

**제가 너무 용어들을 혼합해서.. 다시 범위명을 정의하면..
"chain of trust(신뢰 체인)에 포함되는 CA들의 인증서 리스트 동기화 수행" 입니다.
이 인증서 리스트가 있어야 노드가 "자신이 신뢰받는 CA로부터 서명된 인증서를 가지고 있다(정당한 네트워크 멤버다)" 라고 증명할 수 있을 것 입니다.**

아래는 간단한 신뢰 체인의 예시(?) 입니다.
![image](https://user-images.githubusercontent.com/32866399/40634451-0982cde2-6330-11e8-83bb-24b31511ec47.png)



3. 시퀀스 다이어그램은 발표자료에 설명용으로 그려보긴 했는데 이렇게 그리는게 맞는지 의문이라.. 조언 부탁드립니다..! 

<노드 등록 절차>
![image](https://user-images.githubusercontent.com/32866399/40634338-60a12df4-632f-11e8-9614-de2e3e3b3bff.png)

![image](https://user-images.githubusercontent.com/32866399/40634360-802ad7a6-632f-11e8-9800-32411e71e572.png)

(adminCredential은 admin이 자신을 인증할 때 사용하는 정보로 'ID/PW', '토큰?', 'OTP' 등등 여러가지가 될 수 있을것입니다.)

@junbeomlee 발표자료는 미완성인 자료라서.. 정리가 되면 리드미로 올려도 될까요!?

**Comment by ghost** [comment]
@byron1st , @junbeomlee 

안녕하세요! :)

일단은 다른 서비스 보면서 흉내를 내보려고 auth service 디렉토리 구조를 아래와 같이 정리해봤습니다.

-api
-infra
command.go
event.go 
certificate.go -> 메시지 검증 시 사용할 인증서 모델(?)
key.go -> 메시지 서명 시 사용할 키 모델(?)
message.go -> 서명/검증 필요한 메시지 모델(?)
sign_service.go -> 서명에 대한 기능
verify_service.go -> 검증에 대한 기능
credential_store_service.go -> 키, 인증서 관리 기능
enroll_service.go -> 노드 등록 기능

모델이라는 개념을 표현하는게 어려워서.. 알맞는 표현인지는 모르겠네요 :( 어떠신가요..?

그리고 리드미나 구현디테일에 정리할 내용중 노드 등록 절차를 아래 처럼 표현해봤습니다만 어떠신지..
(생성된 키나 발급된 인증서의 저장은 또 다른 기능이라 제외했습니다)

![image](https://user-images.githubusercontent.com/32866399/40826129-b73a4cc2-65b4-11e8-8e23-60926dbc82b0.png)

**Comment by ttkmw** [comment]
와우 석사과정이셔서 그런지 서류가 엄청나네요..! 곧 제대로 읽어보겠습니당

**Comment by junbeomlee** [comment]
@owljoa 
key.go -> 메시지 서명 시 사용할 키 모델(?)
message.go -> 서명/검증 필요한 메시지 모델(?)
sign_service.go -> 서명에 대한 기능
verify_service.go -> 검증에 대한 기능

key는 heimdall의 key와는 다른 key인가요??!! 
message는 biforst/pb 안에 이미 정의되어있습니다!!
key가 heimdall이라면 sign과 verify는 이미 구현되어 있어서 그것을 사용하면 되지 않을까요?!

나머지는 맞는 것 같습니다!! 그리고 보시면 아시다시피 bifrost와 heimdall, auth, gateway쪽이 연관도가 높아서 합쳐서 진행할 수도 있을 것 같습니다!

**Comment by ghost** [comment]
요거 닫고.. 준범님과 구조 상의해서 doc으로 찾아뵐게요!
