### ISSUE TITLE
각 서비스별 디렉토리 구조 제안

### ISSUE THREAD

**Issue by byron1st** [DE-labtory/it-chain#190]
현재의 디렉토리 구조가 복잡하고 진입장벽으로 작동한다고 생각해서 @junbeomlee 님과 얘기를 좀 해봤습니다. 그래서 다음과 같이 구조를 변경하는게 어떨지 제안합니다.

```
Component
  ⊢ api
  ⊢ infra
      ⊢ rabbitMQ
      ...
  ⊢ model_A.go // include model and repository
  ⊢ model_B.go // include model and repository
  ⊢ service_1.go // only service code
  ...
```

`Component`는 우리가 현재 서비스 라고 부르는 단위로, Consensus, Blockchain, TxPool 등이 여기에 해당합니다. 각 디렉토리 내에는 `api` 패키지(폴더), `infra` 패키지(폴더)가 존재하고, 기존의 model, repository, factory, service 등은 모두 최상위 디렉토리 내에 `go` 파일로 위치시킵니다. model과 repository는 서로 1:1로 매핑되므로 한 파일에서 정의하고, service는 따로 파일을 만듭니다.

`api` 패키지 내에는 더 이상의 서브 패키지 생성을 되도록 자제하고, `infra` 패키지 내에는 각 기술명들이 서브 패키지로 위치하도록 합니다.

@junbeomlee 님이 TxPool을 현재 시범삼아 변경 중에 있으니, 곧 참고하실 수 있을 걸로 보입니다. 

질문이나 의견 있으시면 주셔요~!

**Comment by junbeomlee** [comment]
go가 기존의 프로그래밍 언어들과는 다른 스타일의 pkg구조를 가지고 있기 때문에, java, c#에서 사용되는 기존의 pkg구조를 그대로 옮기기에는 잘 맞지 않는다 판단하였고 uk golang conference강의를 보던중에 
DDD를 go패키지 스타일로 구현한 예제를 발견하였습니다.(https://github.com/marcusolsson/goddd) 좋은 예제의 코드지만 infra를 독립적인 서비스단위로 나누지 않고 하나의 최상의 패키지에서 처리해서 외부 의존성이 생긴다는 점과application service와 domain service의 구분이 어려운 점을 보완하여 위와 같은 코드의 pkg구조를 제안하게 되었습니다. 

최대한 빠르게 txpool를 예제로 올릴 계획입니다!!

**Comment by hea9549** [comment]
좋은 반영인 것 같습니다.

지금 작업중인 peer 쪽도 반영해서 올리도록하겠습니다!

**Comment by zeroFruit** [comment]
확인이 조금 늦었네요.
훨씬 더 직관적인 것 같습니다!
다른 분들 하신 것 보면서 반영해보도록 하겠습니다. 👍
