### ISSUE TITLE
logical architecture kr 에서 Strategic Model Design그림 화질 이슈

### ISSUE THREAD

**Issue by junbeomlee** [DE-labtory/it-chain#197]
Strategic Model Design그림이 화질이 조금 깨지는 거 같아서 더 좋은 화질의 그림으로 그리면 좋을 것 같습니다!!
그림도 legend 같은걸 달아서 Logical Architecture of it-chain처럼 그리면 더 좋을 것 같네요!

**Comment by frontalnh** [comment]
반영하겠습니다!
해당 그림은 draw.io 로 작성하였는데 혹시 괜찮은 툴이 있다면 추천가능할까요? ㅋㅋ

**Comment by junbeomlee** [comment]
@byron1st 님이 사용하는 tool제일 좋아보이고 차선으로는 star.uml이 무료이니 한번 사용해보세요!

**Comment by frontalnh** [comment]
@junbeomlee 해당 내용 수정하였으며 화질은 좀 크게 해보았는데 어떨지 모르겠네요 ㅋㅋ 확인후 issue close 혹은 수정사항 코멘트부탁합니다.
