### ISSUE TITLE
p2p 컴포넌트 개발 시 논의 사항

### ISSUE THREAD

**Issue by frontalnh** [DE-labtory/it-chain#212]
P2P 컴포넌트를 개발하다가 다음 내용에 대해 논의가 필요한 부분이 있어 이슈를 작성합니다.

1. P2P 네트워크 내에 새로운 노드가 참여하는 경우 기존 네트워크에 참여하고 있는 노드들의 정보를 전부 가져와야 하는데 언제, 누구에게 가져올지에 관한 내용이 정리되어야 할 것 같습니다.
이 부분에 대해 정의된 내용이 있다면 댓글 부탁드리며, 만약 정의가 되어있지 않다면 dial 한 노드로 부터 leader의 정보를 받아와 leader에게 기존 node들에 대한 정보를 받아오는 것으로 결정하는 것에 문제가 없는지에 대한 의견을 부탁합니다.

또한, 이 경우 여러 노드들 사이에서 동기화 문제로 노드에 참여하고 있는 참여자들에 대한 리스트에 inconsistency가 발생할 수 있을 것 같은데 이 부분에 대한 의견도 부탁드립니다.

2. 리더를 어떻게 선정하는가?
제가 알고있는 바로는 최초의 노드는 리더가 없고 두번째 이후의 노드가 네트워크 내의 다른 노드에게 dial 하는 시점에 만약 dial을 받은 노드가 leader repo 내에 leader의 정보가 있다면 해당 leader를 전달하고 만약 leader repo가 비어있다면 수신받은 노드가 leader가 되어 네트워크에 전파되는 것으로 이해하였는데 제가 이해한 내용이 옳바른 것인지 혹은 다른 선정기준이 필요할 지에 관한 논의가 필요할 것 같습니다.

3. 아래 그림에서 5 이후의 상황에 관한 논의입니다.
![thirdnodecreatedscenario](https://user-images.githubusercontent.com/25814035/40882751-d10d868c-6726-11e8-9ed0-4ac7c3cdf4f4.png)

새로운 노드가 참여하여 connection이 발생 시 p2p에서 event handler를 통해 노드를 생성하고 이에 대한 5번 이벤트를 발생시키고자 합니다. 이 경우 Gateway에서 event handling 을 통해 다른 노드들로 새로운 노드가 네트워크에 추가되었음을 알려야 하는데 이 경우 connection manager에서 가지고 있는 연결된 노드들에게만 노드가 추가됨을 알릴것인지 아니면 node repo에 저장된 모든 노드들에게 이 사실을 알릴 것인지에 대해 정해진 내용이 있다면 답변부탁드립니다.

4. 현재 새로운 노드 생성시 노드 id를 event의 aggregate id로 사용하는 것 같습니다. 이부분에 대한 확정된 내용을 알려 주시면 문서화 하겠습니다.

5. 현재 amqp의 topic의 종류들에 대해 알려주시면 해당 내용도 문서화 하고 싶습니다.

**Comment by hea9549** [comment]
지금 작업을 할수있는 여건이안되서 ㅠㅠ 오차피 피어의 개발은 주로 형과 제가 맡고있으니

둘이 어느정도 합의하고 진행하면 될 것 같습니다.

1. 먼저 피어테이블의 경우 다이얼을 건 대상 노드의 피어테이블을 가져올 생각입니다.
 추후 블럭 데이터를 받아오는 부분은 blockChain의 서비스가 담당하게됩니다.
리더정보 역시 해당 다이얼을 건 노드로부터 받아옵니다.
맨 처음 it-chain을 구동하여 p2p서비스가 돌기 시작하면 기본적으로 자기 자신이 리더가됩니다.
그 후 다른node에게 다이얼을 하면 해당 node의 리더정보를 받아 적용하고,
다른 node로부터 다이얼이 오면 리더정보를 제공합니다.

피어테이블 및 리더정보의 불일치는 아직 구상된 바가 없습니다.
새로 작성해주셔야해요 ^.^; (하트비트-시퀀스 방법을 통해 동기화지속 등 여러방안을 생각해봐야겠네요)

2. 리더선정 알고리즘같은경우 지금은 일정 주기로 라운드 로빈 방식처럼 돌아가면서 리더를 하는 방안으로 구상중입니다. 리더 선정 알고리즘은 다양합니다.
일단 베타의 목표는 간단하게 라운드로빈 또는 고정 리더로 선출하게 해둔 후 추후 config를 통해 알고리즘을 골라 적용할 수 있도록 확장 예정입니다.

위의 1번에서도 언급했지만 최초의 노드는 자기 자신이 리더가 되게됩니다.

3. NodeRepo의경우 내가 가지고있는 PeerTable이라 생각하면 될 것 같습니다.
먼저 Node와 Peer에 대한 정의를 확실히 할 필요가 있을 것 같습니다.


Node 는 하나의 접속정보를 가지고있는 컴포넌트를 말합니다. 키를 기반으로 생성된 NodeId와 ip주소+포트인 Address를 가지고있습니다.
Peer의 경우 따로 구조체를 가지고 있지않습니다만 내 Node에서 연결된 Node들을 Peer라고 부르려고합니다.
무튼 제가 정한거라 이상한 점 이나 고칠방향있으면 말해주세요!

다시 5번이벤트의 경우 저도 만들어뒀는데 아직 푸시를 못해서...

    //publish
    type PeerCreateEvent struct {
    	    midgard.EventModel
    	    Address string
    }

    //publish
    type PeerRemoveEvent struct {
        	midgard.EventModel
    }


와 같이 만들어뒀네요. 나중에 모든 Connection이 Peer 가 되는것이아닌 선별작업 로직이 들어 갈 것을 대비해 남훈이형이 제시해준 5번이벤트와 같은 이벤트를 만들어뒀습니다.

그 후 Grpc를 통해 내 Peer들에게 알려주어야하는데 기본적으로 모든노드에게 메세지를 뿌릴것으로 생각합니다. ( 베타 목표 )

4. 노드 생성시 노드 id를 event aggregate id로 사용하는 것이 맞습니다. 이벤트 소싱으로 노드 id를 통해 event들을 재적용시키면 해당 id의 노드의 최신 상태를 얻게됩니다. 이를 위해서는 같은 id (정확히는 event의 id가 노드 id가 되야되는 것이겟네요)가 되야겟네요

5. amqp의 topic의 경우 대부분 midgard에 의해 자동적용됩니다.
예외인 부분은 grpcMessageCommand 직접쏴주기 등..? 이것은 @junbeomlee 에게 받으면되겠네요


이상한 부분이나 고치고싶은 방향이 있으면 말해주세요

p2p 부분은 주로 형이랑 제가 담당하고있고 아직 정해진 부분이 많지않아

우리가 방향을 잡고 개발을 하면될 것 같아요~!

**Comment by frontalnh** [comment]
옷 정확한 답변 고맙습니다.
@hea9549 
1. 어 피어테이블 안쓰고 리더 repo 사용하는 것 아니었나요 ㅋㅋ 안쓴다고 했던거 같아서 다 제거했는데 peer table사용한다면 제 풀리퀘와 차이가 많이 있을거 같은데 풀리한번 걸어주세요 ㅋㅋ
또 하트비트 시퀀스?! 는 제가 모르는 내용이라 찾아봤더니 나오지를 안내요 관련 url 이나 혹은 영문 명칭을 알 수 있을까요?

2. 가령 리더가 죽는다던가 하는 경우 새롭게 리더를 선출해야 하는데 이런 경우에도 혹시 정의된 내용이 있나요? 라운드 로빈 방식이라면 피어테이블에서 다음 피어로 시간 간격을 두고 돌아가면서 리더가 선출된다는 의미인가요? 맞다면 이 경우도 마찬가지로 현재 리더가 사망하여 재선출이 필요한 경우 재선출 알고리즘이 필요할거 같은데 이 경우 정해진 내용이 있다면 답변 부탁드리고 없다면 제가 초안을 작성해 보겠습니다.

3. 노드와 피어 둘중 하나를 완전히 체택하는것이 좋을 것 같습니다! 저 같은 경우 중도에 참여하다 보니 초반에 혼동이 많았었어서 훗날 참여하는 개발자가 혼동을 하지 않기 위해 repo 혹은 model과 동일한 명칭을 쓰는게 어떤가 싶습니다. 만약 위의 이벤트를 만들었다면 그냥 peer를 모델로 삼고 가도 될거 같긴합니다만 peer 에서 node로 모델을 변경한 사유가 무엇이었죠??
음 private 노드에서 참여하는 최대 peer 수가 몇개인지는 모르겠지만 전체로 연결을 해도 무리가 없을까요?

4,5 해당 내용은 잘 이해하였습니다

**Comment by hea9549** [comment]
1. 하트비트를 이용해 지속적으로 노드의 연결상태를 체크하고 리더정보를 받았을때 다수의 정보를 따라가거나 또는 리더정보를 요청하는 메세지를 통해 받아올 수 있을 것 같습니다.


2. 정해진 내용이 없습니다.


3. 맨처음 컴포넌트이름이 Peer여서 햇갈리는 이유도 한몫해서 Node로 변경했었습니다!
Peer는 동료? 약간 연결된 다른 개체의 느낌이라 구조체 하나는 Node로써 데이터 구조를 정하고
연결된 Node를 Peer라 하여 의미적으로 사용하려했습니다.

Private Chain에서 BFT 알고리즘계열은 피어 전체를 연결을 합니다. 이때 최대 참여노드수는 약 100부터 300정도 입니다. 그 이상으로는 성능이 확 죽는다고 알려져잇습니다. 준범리의 의하면 100 정도부터도 확 주는다고 하네요. 전체연결을 가정하지않고가려면 합의 알고리즘을 BFT계열이아닌 다른방법을 채택해야할 듯 합니다.

베타버전은 PBFT 알고리즘으로 합의를 진행하고 이에 맞춰 p2p 컴포넌트도 모든 피어를 연결하는 옵션을 베이스로 가져가려고합니다.

Peer의 말이 햇가린다면 그냥 Node로 모두 통일해도 될거같은데 저는 구현할 때 p2p 내부의 정책에 의해 모든 Node가 내 Peer가 되지않을 수 있어서 분리했는데 어떻게하면 좋을까요?
