### ISSUE TITLE
rabbitmq topic, event naming 모델 제안

### ISSUE THREAD

**Issue by junbeomlee** [DE-labtory/it-chain#213]
지금 여러가지로 이슈가 되고 있는 부분이 rabbitmq에서 topic 이름입니다. 이슈를 설명 하기전에 정리 내용이 필요해서 먼저 자세히 설명을 하고 이슈 해결방안에 대해서 논의 하고자 합니다.

rabbitmq를 통해서 2가지가 전달될 수 있는데 command, event입니다. 

1. command는 어떤 요청이라고 보면 될 것 같습니다. user를 생성한다던지, consensus를 시작한다던지 하는 것이 command이며 command요청 객체의 naming convention을 ConnectionCreateCommand, TransactionCreateCommand 식으로 하고있습니다.
2. event는 command를 통해 내부 state(aggregate)가 변하게 될 경우 발생하는 것입니다. 예를 들어 TransactionCreateCommand에 의해 성공적으로 transaction이 생성되었다면 TransactionCreatedEvent가 발생할 것입니다. 

2개의 특성이 좀 다른데요!! command같은 경우는 상대가 보통 1명으로 지정되어있는 경우가 많고, event경우에는 상대와 상관없고 존재한다면 여러명을 대상으로 발생시키기 때문에, command는 direct 방식으로 event같은 경우에는 topic 방식으로 합니다. 
https://www.rabbitmq.com/tutorials/tutorial-five-python.html

지금 midgard에 구현된 rabbitmq는 모두 topic기반으로 publish하고 있는데 2개로 나누어서 client를 만들지가 일단 첫번째 이슈이고 이부분에 대해서 의견 주시면 감사합니다. 그리고 rabbitmq client를 별도의 library로 분리할 계획을 하고 있습니다.

topic기반일 경우 topic선정 기준에 대한 이야기가 많이 나오고 있는데 현재는 connection에 관련된 command일 경우에는 topic = "Connection", Transaction에 관련된 command일 경우 topic = "Transaction"이라고 했는데 이 부분이 어떤 행동에 대한 의미를 유추하기 어렵다고 하여 Command이름과 동일하게 하면 어떨까 합니다. ConnectionCreateCommand면 topic="connection.create" 이런식으로 처리하는 것으로 이렇게 될 경우 subscribe하는 곳에서 subsrcrbe("connection.*",handler{})할 경우 connection.xxxx패턴에 맞는 모든 메세지를 consume하기 때문에 topic한개로 여러 subscribe를 수행 할 수 있습니다!!

**Comment by junbeomlee** [comment]
@hea9549 @frontalnh @zeroFruit

**Comment by junbeomlee** [comment]
1. topic pattern에 대한 의견 
2. rabbitmq client를 topic, direct로 구분 문제에 대한 의견 
부탁드립니다

**Comment by frontalnh** [comment]
1. 좋은 것 같습니다! 추후 규모가 커지는 경우 단일 topic의 세부 내용에 따라 별도의 handler를 부여하여 협업이 쉬워지는 등의 장점이 있을 것 같습니다.
2. 개인적으로 topic으로 통일하는 것에 한표 던집니다 ㅎㅎ

**Comment by ttkmw** [comment]
1.자유도가 높다는 점에서 다른 패턴보다 좋아보입니다. 메시지가 버려지지 않도록 topic 선정 기준을 명확히하고 문서화한다면 direct 패턴보다 나쁠 것이 없어 보입니다(topic 선정 기준은 본문에 써주신 대로 하면 좋을 것 같습니다.).
2.command, event에 대한 publish 방식을 나눌 지: topic 방식도 direct처럼 쓸 수 있기 때문에 굳이 나누지 않아도 될 것 같습니다.
