### ISSUE TITLE
map을 이용한 test case 작성

### ISSUE THREAD

**Issue by zeroFruit** [DE-labtory/it-chain#225]
@junbeomlee 
요즘 map string을 이용한 test case 작성이 많이 보이고 있는데
처음에는 좋아보였는데 계속 보다보니까 한눈에 test case가 어떤 동작을 하는지 알기가 조금 힘든 것 같습니다.

1. 저는 주로 test case를 보면서 각 객체들이 어떤 의존성을 가지고 있는지 파악하는데 for loop에서 test.input과 같은 방식으로 인자들을 넘겨주다보니까 계속 위아래로 봐야하는 불편함이 조금 있네요

2. 위아래로 보는게 case가 적고, 인자들이 적으면 그렇게 불편하진 않는데 case가 여러개이고 인자가 조금만 길어져도 한눈에 파악하는게 힘들어지는 것 같습니다.

3. success\/fail case를 한 test function에 넣지 말고 Test<Object>\_<FuncName>\_Success, Test<Object>\_<FuncName>\_Fail 이런식으로 분리하면 어떨까요? 그런데 이렇게 하면 map을 쓰는 이유가 없어지겠네요

test 코드를 보다보니까 갑자기 떠올라서 이슈남깁니다.

**Comment by junbeomlee** [comment]
tdd라고 table driven design이라는 방식의 테스트 방법인데, 위에 같이 하는게 원래 정석 테스트 케이스 작성방법이지만 이렇게 작성하는 이유는 같은 함수를 테스트 하는 것이기 때문에 setup하는 과정에서 중복이 일어나서 테스트 케이스를 table로 만들어 처리하는 패턴입니다. 완전히 명확하게 테스트 케이스틑 표현하기 위에서는 위와 같은 방식이 맞는 방식인 것 같습니다. 이부분에 대해서는 토요일에 제가 발표하는 테스트 파트를 설명드리고 그 후에 다같이 얘기 나누면 좋을 것 같습니다. 그날 테스트 틀을 명확히 정해보는것도 좋을 것 같아요!
