### ISSUE TITLE
command 묶어내기

### ISSUE THREAD

**Issue by zeroFruit** [DE-labtory/it-chain#243]
코드를 작성하다보니까 다른 컴포넌트의 command가 어떻게 생겼는지 알아야할 필요가 있더라고요.
byron1st님께서 작성해주신 코드에서 txpool => blockchain: SendProposeBlockCommand 같은 예시에서도 txpool에서 blockchain transaction domain을 알아야할 필요가 있더라고요.(현재 코드에서도 blockchain ProposeBlockCommand에서 txpool의 transaction을 참조하고 있는(txpool과 blockchain의 transaction model이 너무 달라서) 더러운 형태가 되었습니다)

command부분이 여러 컴포넌트 간에 공통으로 알고있어야하는 부분인 것 같아서 command가 domain이 아니라 밖으로 끄집어내야하는게 아닌가 싶습니다.

**Comment by frontalnh** [comment]
찬성합니다 event도 같이 빼도 될것 같기도 하구요ㅋㅋ
공통 doc의 경우 event와 command의 doc의 it-chain-event에 작성하는 곳이 있기는 합니다!

**Comment by junbeomlee** [comment]
이부분에대해서는 여러번 얘기가 나온 부분 이긴 한대, command는 요청 객체이기 때문에 다른 컴포넌트의 command를 알아야하는것은 당연한 부분이고, event도 내가 다른 컴포넌트에 관심이 있는 것이기 때문에 event구조도 알아야 하는 것또한 마찬가지입니다.

다른 DDD예제들을 보면 모두 event,command를 중복으로 가지고 있고(공통 event로 분류하지않음) 그 이유가 제 생각에는 MSA자체가 중복을 허용하고 self-contained를 더 중요시 여기기 때문이라고 생각이 듭니다. 제 생각으로는 core라는 패키지로 domain model(block, transaction)등을 분리하는것이 좀더 좋은 방향일것 같습니다.

처음에 원래 event를 common 패키지로 분리했었는데 오히려 누가 어떤 이벤트를 발생시키는건지가 더 헷갈려서 현재 구조로 넘어왔습니다.

**Comment by hea9549** [comment]
도메인 모두를 Core 패키지로 넘긴다는 말인가요???

**Comment by zeroFruit** [comment]
제가 생각했던 부분은 command, event만인데 command, event에 들어가는 node, block...같은 것은 중간에서도(각 컴포넌트에는 당연히있고) 공통적으로 정의하는게 어떨까였습니다

**Comment by junbeomlee** [comment]
@hea9549 
노노 어떤걸 넘길지를 정해야할듯!!
@zeroFruit 
위에서 말한대로 처음에는 command랑 event를 messaging으로 모두 몰아서 관리 했었는데 그게 좋지가 않아서(누가 어떤 이벤트를 발생시키는건지가 더 헷갈려서 현재 구조로 넘어왔습니다.) 현재의 상태를 가지게 되었고 다른 모든 참조 예제들도 중복을 허용한채로 구현을 하고 있습니다. 
저는 event,command가 아닌 오히려 tx,block같은 core들을 옮겨야 한다고 보고 있고, 그렇게 할경우 command,event의 중복도 많이 줄어들 것 같습니다.

**Comment by zeroFruit** [comment]
core들 옮겨내기 괜찮을 거 같습니다.

**Comment by hea9549** [comment]
Core로 특정도메인만넘기는걸로 합의될경우 
어떤것들을 넘길건지도 정해야겠네요 빠르게추진할가여 ??

**Comment by junbeomlee** [comment]
@hea9549 
추진해주세여..

**Comment by frontalnh** [comment]
각 컴포넌트마다 세부 기능에 대한 정리가 아직 없기도 하고 특정 도메인을 옮기는 기준을 정함에 있어 여러 기능들을 고려해야 할 듯 한데, 기준선정에 어려움이 있을 것 같네요
