### ISSUE TITLE
Consensus 네이밍 관련

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#247]
consensus 부분을 작업하다가 네이밍 관련해서 의견을 듣고 싶어서요!

consensus 내에서 PBFT 알고리즘 중 Pre-prepare, Prepare, Commit 메시지를 주고 받는 일이 필요합니다. 이를 Event로 만들어 처리하는데 이 메시지를 가리키는 말이 "ConsensusMessage" 라고 밖에 생각나지 않습니다ㅜㅜ consensus라는 말을 바꾸고 싶은데 좋은 의견 없을까요?

노드 A가 prepare 메시지를 받았을 때 예를 들면, 노드 A의 consensus 컴포넌트는 ConsensusMessageArrivedEvent를 handle하여 그 메시지가 prepare임을 확인합니다. 여기서 event에  "consensus"라는 말이 자꾸 붙는데 패키지 이름도 consensus여서 애매모호합니다.

**Comment by hea9549** [comment]
기존코드는 도메인/모델/msg/commit_msg ,prepare_msg 등으로 되어있습니다.

지금은 도메인을 따로 패키지로 빼지않으니

그냥 msg 파일을 하나 생성해서

컨센서스/msg.commit, prepare, pre-prepare 로 가는건 어떤가요?

아니면 각 메세지가 커질것같으면 패키지로 msg를 구성해서

consensus/msg/commit, prepare , pre-prepare 로 가는거도 괜찮은것같습니다.

**Comment by junbeomlee** [comment]
아예 패키지를 pbft로 바꾸고 pbft.preparemsg는 어떤가요?

**Comment by hihiboss** [comment]
@junbeomlee 

`it-chain-Engine/consensus`
대신
`it-chain-Engine/pbft`
이렇게요??

consensus 모듈의 패키지명은 consensus가 아니라 pbft가 되는건가요?!

**Comment by junbeomlee** [comment]
ㅇㅇ 아니면 consensus패키지에 message라고 그냥 해도 될거 같기도 하고...모르겟다 킥

2018년 6월 27일 (수) 오후 2:50, KimJunHui <notifications@github.com>님이 작성:

**Comment by hihiboss** [comment]
그럼 일단 message.go 안에 PrePrepareMsg 이런 식으로 만들겠습니당ㅎ
