### ISSUE TITLE
GrpcCommand 문서화가 필요할 것 같습니다.

### ISSUE THREAD

**Issue by frontalnh** [DE-labtory/it-chain#252]
현재 gateway에서 grpc command 들의 매개물로써

보낼때는 gateway가 MessageDeliverCommand 를consume 하여 send하고
메세지 받으면gateway가 MessageReceiveCommand 를 publish하여 각 컴포넌트에서 consume하게 하는데

제가 알기로 midgard 가 command의 structname을 기반으로 동작하는 것으로 아는데 위 두 종류의 커맨드가 여러 컴포넌트 내에서 사용될때 이름이 변질되고 있는 것 같습니다.

제 설명이 맞나요? 이거 어떻게 통일할까요?

@junbeomlee
@hea9549 
@zeroFruit 
@junk-sound

**Comment by frontalnh** [comment]
설명이 맞다면 개인적으로
GrpcDeliverCommand
GrpcReceiveCommand

한표 던집니다!

**Comment by zeroFruit** [comment]
보낼 때는 각 컴포넌트 입장에서 네이밍되고, 받을때는 gateway 입장에서 네이밍되는게 좋은 것 같습니다
이제 개인적으로 message라는 단어는 별로쓰고 싶지않아서 @frontalnh 제안한 네이밍 좋은 거 같습니다.

**Comment by frontalnh** [comment]
의견 수렴되면 logical architecture에 제가 반영하겠습니다!

**Comment by junbeomlee** [comment]
GrpcDeliverCommand
GrpcReceiveCommand
이거 2개로 통일하고 grpc관련 command는 모두 
이 2개로만 처리됩니다!~

**Comment by junbeomlee** [comment]
@zeroFruit 보낼때도 GrpcDeliverCommand에 맞춰줘야 합니다
요청마다 다른 파라미터들은 GrpcDeliverCommand안에 있는 body에 json marshal로 넣으면 됩니다.

**Comment by junbeomlee** [comment]
그리고 지금 gateway에 있는 2개가 midgard.CommandModel안되어있어서 그거 추가해야 할것 같네요!

**Comment by frontalnh** [comment]
gateway 는 @junbeomlee 가 하는 겁니까? ㅋㅋㅋ

**Comment by zeroFruit** [comment]
👍

**Comment by junbeomlee** [comment]
얼른해봄 ㄱㄷ 조금걸림 4~5시?

**Comment by frontalnh** [comment]
그냥 바쁘면 건드려 볼라했었음 ㅋㅋ ㅇㅋㅇㅋ
