### ISSUE TITLE
txpool 보완점

### ISSUE THREAD

**Issue by hea9549** [DE-labtory/it-chain#267]
![image](https://user-images.githubusercontent.com/20393677/42075878-e9c9a598-7bad-11e8-85e8-619318bbae96.png)

현재 코드인데 
19라인의 txRepository.FindAll 하고나서 

![image](https://user-images.githubusercontent.com/20393677/42075979-32dc9eac-7bae-11e8-833f-b640e7967625.png)

이부분에서 보내고 난 뒤 삭제를 안하고있어서 무기한쌓이고 무기한 보내게될 것 같네요

수정필요!

그리고 batcher에 등록하는부분이나 repo 주입부분이없는거보니 미완인듯?

누가만든지 모르겟으니 둘다태그

@junbeomlee @frontalnh

**Comment by hea9549** [comment]
미완인 부분은 투두에잇네여 핫 하튼 delete하는쪽

**Comment by junbeomlee** [comment]
ㅇㅇ 미완 하지만 자세한 todo 굳이염 somebody help!!!

**Comment by junbeomlee** [comment]
publish topic도 옛날꺼인듯 수정 해야 할듯요!

**Comment by zeroFruit** [comment]
머지 기다릴 동안 해볼까요?ㅋㅋ

**Comment by junbeomlee** [comment]
ㅇㅇ 그리고 보완할점은 많아 보이니 한번 잘 업그레이드 고고!!
