### ISSUE TITLE
mock pkg 제안 by namhoon

### ISSUE THREAD

**Issue by junbeomlee** [DE-labtory/it-chain#286]
같은 mock객체가 다른곳에서 다르게 만들어 지고있는데, 루트 pkg의 test/mock 형태로 mock객체를 정의하고 공유하는것을 @frontalnh 이 제안했습니다!! 좋은것 같고 적용 예시를 @frontalnh 이 올려주기로 했으니 같이 보고 얘기하면 좋을 것 같습니다!

**Comment by frontalnh** [comment]
@junbeomlee @junk-sound @zeroFruit @hea9549 @hihiboss 
위 p2p의 leader_api_test, test/mock 들에 예시 코드를 작성해 보았습니다!
