### ISSUE TITLE
readme requirement에 rabbitmq, mongodb 추가

### ISSUE THREAD

**Issue by junbeomlee** [DE-labtory/it-chain#300]
## Requirements

- Go-lang >= 1.9
- Docker >= 17.12.0

**Comment by gy741** [comment]
This issue has been resolved.

commit: 9c5d9bab6d249f30a1268a58085b7580165c2789 and a404f80f8d21b1a6820fde70b3b9db419502c1aa

**Comment by junbeomlee** [comment]
thank you
