### ISSUE TITLE
[blockchain] Refactor block api, CheckAndSaveBlockFromPool

### ISSUE THREAD

**Issue by zeroFruit** [DE-labtory/it-chain#352]
현재 blockchain/block_api CheckAndSaveBlockFromPool함수가 못생겼습니다.
같이 blockchain 부분을 작업하고 계신 @junk-sound 님과 초반에 얘기했을때는 다음과 같이 수정하려고 했습니다.

```
func ConfirmBlock[api] (blockId) {
    ...
    if (IsBlockSyncNeedToDo[service]) {
        Synchronize[api]     
    } else {
        // publish SaveBlockCommitedEvent
    }
}
```
 과 같았습니다. **`ConfirmBlock`은 `CheckAndSaveBlockFromPool`함수의 가제로 썼습니다.** 현재 block sync가 필요한지 체크한 후, 필요하다면 `Synchronize` api함수를 호출하는 것입니다. 그런데 다른 방법이 떠올라서 제안해봅니다.
```
func ConfirmBlock[api] (blockId) {
    ...
    if (IsBlockSyncNeedToDo[service]) {
        PublishBlockSyncEvent[service]     
    } else {
        // publish SaveBlockCommitedEvent
    }
}
```
차이점은 싱크가 필요할때 Syncrhonize를 해달라고 이벤트를 날리는 것입니다. 이부분은 service단에서 해결하게됩니다. 이렇게 생각하게 된 이유 및 장점은 다음과 같습니다.

* ConfirmBlock이 너무 많은 일을한다(직접 Sync호출)
* Syncrhonize함수를 몰라도된다.
* 이벤트를 날려서 다른 일을 하도록 시키는 것이 이벤트 소싱에 좀 더 맞다고 생각했습니다.

피드백 부탁드립니다! @junbeomlee @junk-sound @byron1st @frontalnh @hea9549 

**update**:
`ConfirmBlock`은 어떤 네이밍이든 될 수 있습니다. 현재 임시로 정해놓은 상태입니다.

이 함수에 대해 다른 아이디어도 나와서 같이 올립니다. 위와 같이 if..else로 sync를 하던지 commited event를 날리던지 둘 중 하나만 하는 것이 아니라, 싱크를 하던 말던 stage된 블럭을 commited로 바꾸는 것입니다. 
이 부분은 Syncrhonize construct부분에서 저장할때 저장하는 repository부분에서만 신경 써 주면 좋을 것 같습니다.

comment(junk_sound): 싱크를 하던 말던 stage된 블록을 committed로 바꾸는 것이 아니라, 현재 lastBlock의 height이 staged된 블록들과 안맞아서 Synchronize를 수행했을 경우에 동기화를 수행하고나서 바로 stagedBlock을 처리해주는 로직을 말한 것이었습니다. 현재는 Synchronize를 해서 staged 블록을 commit할 수 있는 경우에도 다음 confirmed 블록을 받아야 staged된 블록들을 처리하는 로직이기 때문입니다. 
싱크를 하던 말던 staged 블록을 committed로 바꾸면 안되죠!
```


func ConfirmBlock[api] (blockId) {
    ...
    if (IsBlockSyncNeedToDo[service]) {
        ...   
    }
    // publish SaveBlockCommitedEvent
    
}
```

**Comment by ttkmw** [comment]
음 저는 ConfirmBlock에서 Synchronize가 호출된다고 생각하진 않았습니다

**Comment by ttkmw** [comment]
ConfirmBlock이 도메인 함수인 것같은데요.

CheckAndSaveBlockFromPool안에서
IsSyncNeedTodo를 하고
필요하다고 생각 되면 
Synchronize를 하는 거라고 생각했습니다.

ConfirmBlock은 saged -> committed로 state 변경하는 역할만 하면 좋을 것 같아요.(Synchronize내에서 사용되는 construct와 유사한 역할이라고 생각합니다.)

**Comment by zeroFruit** [comment]
ConfirmBlock은 api 함수입니다.

**Comment by ttkmw** [comment]
그러면 도메인으로 내리는게 좋을 것 같습니다 ㅋㅋㅋㅋㅋ

**Comment by ttkmw** [comment]
저는 CheckAndSaveBlockFromPool 이거만 api에 남기고 나머지는 다 도메인으로 내리는 게 좋다고 생각합니다.

**Comment by zeroFruit** [comment]
일단은 아직 명칭은 좀 더 생각해봐야할거같습니다. 지금 이 이슈의 핵심으로 synchronize api를 직접호출하냐 아니면 event를 날려서 실행시키면 좋을거냐라는 의도로 올렸습니다!

**Comment by junk-sound** [comment]
제 생각에는 현재 관련된 aggregate가 없고 event handler에서는 상태 변화만 시켜주기 때문에 Synchronize를 이벤트로 처리하는 것은 안맞는 것 같습니다.

**Comment by zeroFruit** [comment]
이부분은 다시 생각해보니 그냥 api를 호출하는게 더 편할거같습니다! 원래대로 진행할게요
