### ISSUE TITLE
[blockchain] blockchain 컴포넌트 Refac

### ISSUE THREAD

**Issue by ttkmw** [DE-labtory/it-chain#372]
@zeroFruit 님이 수고해주신 덕분에 현재 develop 브랜치의 블록체인 컴포넌트는 오류가 없지만, 코드를 새로 작성하다보면 객체가 겹쳐 쉽게 오류가 생깁니다(특히 blockApi).

이를 개선할 겸, 다음과 같은 작업을 하면 좋을 것 같습니다.

_**1. 현재 사용하지 않는 코드 제거.**_
_**2. 현재 미완성인 부분의 제거 혹은 주석 처리.**_

1. 현재 사용하지 않는 코드 제거: 지워도 될 것 같은 코드에 대해서는
> ToDo: 삭제 제안 - junk_sound

라고 적어놓겠습니다. @zeroFruit 님도 지워도 될 것 같으면 지우고 커밋 해주시면 감사하겠습니다.

2. 현재 미완성인 부분의 제거 혹은 주석 처리: 제가 작성하지 않았지만 새로운 코드와 겹치는 부분은
>ToDo: 미완성 부분에 대한 주석처리

라고 적어놓겠습니다.

**Comment by zeroFruit** [comment]
👍

**Comment by ttkmw** [comment]
부분적으로 완료하여 close합니다.
