### ISSUE TITLE
[ txpool ] memory db 패키지 위치

### ISSUE THREAD

**Issue by hea9549** [DE-labtory/it-chain#411]
@junbeomlee 
txpool의 repository중 memory repository가 infra 레벨에 있는게 맞나요? 

일반구현체라 infra 레벨이아니라 일반 도메인레벨의 레포지토리로 봐도되는거아닌가욤?

**Comment by hea9549** [comment]
![image](https://user-images.githubusercontent.com/20393677/42932628-c6efed72-8b7d-11e8-8c7c-f05ee1ec4922.png)

**Comment by junbeomlee** [comment]
저거 지워야함여 지워주세요

**Comment by junbeomlee** [comment]
제가 작업중입니다~
