### ISSUE TITLE
[blockchain] clean SendBlockValidateCommand

### ISSUE THREAD

**Issue by zeroFruit** [DE-labtory/it-chain#435]
현재 `commend_service.go` 에서 SendBlockValidateCommand가 쓰이지 않는 것 같아서 삭제하려고 합니다!
그리고 다음부터 commend service를 만들땐 **`xxx_service.go`** 형식으로 만드는 것이 구체적으로 어떤일을 하는지도 알 수 있고 더 좋은 것 같습니다.
@junk-sound 혹시 위 코드 사용하는지 한번 확인해주세요!

**Comment by junbeomlee** [comment]
저는 `xxx_command_service.go`보다 의미있는 이름으로 정하는것이 더 좋을 것 같습니다.
예를 들어 transfer_service라던지 하는 이름이 더 좋은 것 같습니다. 이름이 infra에 종속되는 것 같아서 나중에 transfer_service가 http 혹은 amqp가 될수도 있기 때문에 interface이름은 꼭 도메인 언어로 작성되었으면 합니다. 하지만 구현체는 command가 들어가도 될 것 같습니다.

**Comment by zeroFruit** [comment]
좋은 것 같네요. 수정했습니다
