### ISSUE TITLE
[common] command와 event 통합

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#450]
각 컴포넌트별 command와 event를 합치기로 결정했습니다.

common 패키지 안에 있는 command.go 와 event.go 에 커맨드와 이벤트 이동해주세요!

**Comment by hihiboss** [comment]
command 와 event 적기 전에 주석으로 어떤 컴포넌트에 대한 것들인지 적어주세요!

그리고 패키지가 옮겨짐에 따라 네이밍이 바뀌었습니다. 기존 네이밍에서 `command`, `event`는 빼주세요!

**Comment by hihiboss** [comment]
@frontalnh

**Comment by junbeomlee** [comment]
p2p만남았습니다!

**Comment by frontalnh** [comment]
착수하였습니다.
