### ISSUE TITLE
[icode] TestICodeEventHandler_HandleMetaCreatedEvent Error

### ISSUE THREAD

**Issue by junbeomlee** [DE-labtory/it-chain#452]
func TestICodeEventHandler_HandleMetaCreatedEvent 함수 fail남

**Comment by kshinlee** [comment]
# #This issue is merged pull request(#783)

**Comment by kshinlee** [comment]
This issue is merged pull request(#783)

**Comment by kshinlee** [comment]
This issue is merged pull request(#783)

**Comment by kshinlee** [comment]
This issue is merged pull request(#783)
