### ISSUE TITLE
[Tip] 새로운 파일 생성시 copyright 자동 생성

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#496]
저희 모든 파일 앞부분에 copyright를 작성하도록 했는데, 파일 생성 때마다 번거롭고 추가하는 걸 깜빡해서 커밋을 되돌리는 경우도 있었습니다.
그래서 파일을 생성할 때마다 자동으로 copyright를 작성하도록 하는 설정법을 공유합니다!
(설정은 mac os 기준이나 goland라면 윈도우도 크게 다르지 않을 것 같네요.)

`Preferences` - `Editor` - `File and Code Templates` - `Files` 탭에서 `Go File` 클릭 - `package ${GO_PACKAGE_NAME}` 앞에 copyright 주석을 추가하시면 됩니다!

**Comment by hihiboss** [comment]
@ChaeByunghoon

**Comment by ttkmw** [comment]
와우...꿀팁 감사합니다.

**Comment by frontalnh** [comment]
적용완료!
