### ISSUE TITLE
[ icode ] icode path conf 상대경로 -> 절대경로 자동변환

### ISSUE THREAD

**Issue by hea9549** [DE-labtory/it-chain#503]
[ icode ] icode path conf 상대경로 -> 절대경로 자동변환

현재 icode savepath , ssh path등 상대경로로 입력할시 에러남

ex ) ./.tmp 하면 인식못함

자동으로 절대경로로 변환하는 것 만들어줘야함

**Comment by sinramyeon** [comment]
```
package main

import (
	"fmt"
	"path"
	"path/filepath"
)

func main() {
	base := "/home/bob"
	fmt.Println(path.Join(base, "work/go", "src/github.com"))

	fmt.Println(filepath.Abs("/home/bob/../alice"))
}
```
이런 함수를 추가하면 되지 않을까요? icode path conf설정 해주는 쪽이 어디인가요??

**Comment by hea9549** [comment]
원래 아이코드들 저장되는 경로를 설정해주는게 
conf/config.yaml 파일 에서 지정해주게 되어있었는데 
(conf 파일 관련설명은 conf 패키지 안의 README.md 참고하시면 좋아요!)

지금 conf에서 빠지고 engine/icode/infra/adapter/deploy_command_handler.go 쪽에 Handle Deploy Command 함수를 보면 savePath를 .tmp로 해주고있습니다.

사실 아이코드 파일들 저장할 경로까지 conf로 지정할 필요가 없을 것 같기도 해서 icode savePath는 괜찮을 것 같습니다만,

sshPath는 절대경로로 변환하는 과정이 필요할 것 같습니다.

마찬가지로 HandleDeployCommand 부분 보면 커맨드에서 SshPath 받아올때 \~/.ssh/ssh_rsa 와 같이 입력을 한다면 \~/ 부분을 말씀하신대로 /home/bob 과 같이 유저 홈 디렉토리와 이어줘야하는데
(~/.ssh/ssh_rsa 입력한 것을 함수로 넘겨줄때 /home/bob/.ssh/ssh_rsa 로 변경 )
```go

func (d *DeployCommandHandler) HandleDeployCommand(deployCommand command.Deploy) (icode.Meta, rpc.Error) {

	savePath := os.Getenv("GOPATH") + "/src/github.com/it-chain/engine/.tmp/"
	meta, err := d.icodeApi.Deploy(deployCommand.GetID(), savePath, deployCommand.Url, deployCommand.SshPath)
```

이 부분에서 command 안의 내용을 바꿔서 넘겨줘야 할 것 같습니다
go api 중에 home path 를 불러올 수 있는 부분이있다면 체크하고 변경하는 로직이 필요할 것 같습니다!

추가적으로 icode save path도 conf로 빼고싶으시면 config model쪽 변경하고 savePath 넘길때 conf에서 읽어와서 넘기면 될 것 같습니다~

추가적인 질문사항있으면 코맨트해주세요!

**Comment by sinramyeon** [comment]
sshpath도 동일하게 "/src/github.com/it-chain/engine/.tmp/" 에서 생성되나요? ssh 가 생성이 되는 곳을 안다면

```
func RelativeToAbsolutePath(rpath string) {

	var text string
	gopath := os.Getenv("GOPATH")
	if gopath == "" {
		gopath = build.Default.GOPATH
	}


	if strings.Contains(rpath, "~") {

		pathPrefix := path.Join(gopath, "/src/github.com/it-chain/engine/conf")
		text = strings.Replace(rpath, "~", pathPrefix, 1)	
		
		fmt.Println(text) // 제 경우 /Users/ksh/dev/workspace/go/src/github.com/it-chain/engine/conf/.ssh/ssh_rsa 로 나오게 됨
	}
}
```

식으로 처리하면 될 것 같습니다. `deployCommand.SshPath` 내 ssh파일 저장위치는 항상 동일한가요?

**Comment by hea9549** [comment]
ssh 파일은 it-chain에서 생성해주는 파일이아닌
deploy 하려는 icode에 등록한 ssh 키 쌍의 private key입니다. 따라서
it chian에서 icode를 deploy할때 해당 키의 위치를 입력해줍니다.
예를들어 cli에서 it-chain ivm deploy github.com/hea9549/sampleicode ~/.ssh/id_rsa 와 같이 입력하는식으로, icode마다 ssh가 다를 수 있습니다.
사용자는 it-chain을 통해서가 아닌 open ssh 등과같은 방법으로 미리 prv key를 생성해두어야합니다.
그리고 해당하는 key의 위치를 deployCommand로 넘겨줍니다.

또한 contains로 ~를 찾는방법보다 앞부분의 ~를 찾는게 조금더 안전할것같습니다!
폴더명에 ~가 포함 될 수 있기때문에 버그가 발생할 수도 있을것 같아요

**Comment by hea9549** [comment]
처리되었으므로 클로즈합니다.

**Comment by zeroFruit** [comment]
writing RelativeToAbsolutePath test code. (added two cases)
