### ISSUE TITLE
[blockchain] Creator type 변경

### ISSUE THREAD

**Issue by ttkmw** [DE-labtory/it-chain#556]
block.go 내 DefaultBlock의 Creator의 타입 변경: 

byte -> string

**Comment by sinramyeon** [comment]
@hero0926 작업중이신것 없으시면 진행하겠습니다. []byte -> string
yggdrasil(철자가맞는ㄴ지 모르겠네요 ㅠㅠ)내 block의 get/set 메서드에는 변경이 없나요?

**Comment by ttkmw** [comment]
@hero0926 
아 지금 봤네요 ㅜㅜ
네 진행하시면 됩니다!

yggdrasill 내 common/block.go 의 함수도 바꿔주셔야 합니다!

**Comment by sinramyeon** [comment]
common/event/event.go 내

```

// todo 블록 정보 가지고 있어야 함
// consensus가 끝났다는 event
// true면 블록 저장, false면 블록 저장 안함
type ConsensusFinished struct {
	Seal      []byte
	PrevSeal  []byte
	Height    uint64
	TxList    []Tx
	TxSeal    [][]byte
	Timestamp time.Time
	Creator   []byte
	State     string
}

``` 

는 block 정보 가지고 있다는데 여기도 동일 변경 해야하는 것인가 싶습니다.

또 common/command/command.go 내에 ExecuteBlock

```

//Icode에게 block 내 TxList 실행 command
type ExecuteBlock struct {
	BlockId   string
	Seal      []byte
	PrevSeal  []byte
	Height    uint64
	TxList    []Tx
	TxSeal    [][]byte
	Timestamp time.Time
	Creator   []byte
	State     string
}
```

에도 궁금하네요. Validator나 block query api 등에서 사용 하던데... 통일하는것이 맞지 않는지 싶습니다.
yggdrasil 내에는 PR하였습니다.

**Comment by ttkmw** [comment]
@hero0926 
yggdrasill 에서는 확인하였고, 머지 되었습니다.

네 맞습니다. creator는 모두 싹 다 바꿔야합니다.
