### ISSUE TITLE
[consensus] elect 네이밍 변경

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#561]
연결된 peer 중 합의에 참여할 representative를 뽑는 elect 함수가 consensus 에 존재하는데, p2p의 리더 election과 네이밍이 겹치는 것 같아 이름 수정이 필요합니다.

**Comment by frontalnh** [comment]
set representatives 어떤가요?
뽑는다는 느낌보다는 현재 참여원으로 set 해주는 개념이니까요!
괜찮다면 해당 내용으로 수정하겠습니다

**Comment by hihiboss** [comment]
@frontalnh 
네, 나쁘지 않은 것 같습니다!
수정 부탁드립니다~
