### ISSUE TITLE
[proposal] issue/pull request template 제안

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#567]
Github에서 issue/pull request template 기능을 지원하는것 같네요!

![image](https://user-images.githubusercontent.com/34789831/43518774-04cb1d48-95c8-11e8-908f-4794992bbafe.png)

이런 template를 작성하면 더 일관되고 보기 쉽게 프로젝트를 관리할 수 있을 것 같아서 제안합니다!

더불어, GoLand와 같은 Jetbrains IDE에서 Github과 연동하면 issue number기반으로 branch도 쉽게 만들 수 있는 것 같습니다.

contribution guide나 issue / pull request template, branch 관리 등을 같이 정해서 정리해두면 프로젝트에 참여하기 더 쉬울 것 같습니다 :)

https://cheese10yun.github.io/github-proejct/
이곳에 더 자세하게 설명하고 있어 링크 남깁니다.

**Comment by hihiboss** [comment]
제가 생각한 pull request template은 다음과 같습니다.

```markdown
resolved: #[issue number]
detail : [작업 내용]
- [ ] Test case 작성 여부
```
> template에 resolved 를 달면 해당 pull request가 close 될 때 자동으로 issue도 close 된다고 합니다.

이외에 무엇이 더 들어가면 좋을지 의견 주시면 감사하겠습니다!

**Comment by junbeomlee** [comment]
저정도면 일단 중요한 내용들은 모두 포함된것 같습니다!
