### ISSUE TITLE
[blockchain] clean query api

### ISSUE THREAD

**Issue by zeroFruit** [DE-labtory/it-chain#641]

**Comment by zeroFruit** [comment]
@zeroFruit

**Comment by hea9549** [comment]
좀더 상세 설명이 필요할것같아요

**Comment by junk-sound** [comment]
@junk-sound 제가 처리할게요!

**Comment by zeroFruit** [comment]
이벤트 소싱이 없어지면서, 그리고 각 컴포넌트 내부에 repository를 두기로 결정하면서 blockchain query api 부분에는 commited된, 즉 최종 확정된 블록들만 저장하기만 하면됩니다. 그래서 blockpool repository가 더이상 필요없어지고 created, staged 블록을 따로 저장할 필요도 없어졌습니다.
그래서 변화된 구조에서 필요없는 코드들을 삭제하려고합니다.
