### ISSUE TITLE
[consensus] finished event에 block 정보 담기

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#675]
**Component**
consensus - pbft (common)

**Assignee**
.

**Problem or Necessity**
consensus 합의가 끝나면 blockchain과 ivm에 ConsensusFinishedEvent를 날립니다.
blockchain은 합의된 블록을 저장하고, ivm은 블럭 안의 트랜잭션을 실행합니다.

이를 위해 해당 이벤트에 필요한 정보를 담아야합니다.

**Detail**
blockchain 이 consensus start command를 날린 후 "합의를 요청한 임시 블럭"을 가지고 있다면 블럭의 모든 정보를 가질 필요는 없을 것 같습니다. command를 날리는 과정에서 "합의를 요청한 임시 블럭"을 삭제하고 consensus 로부터 받는 event를 이용하여 블럭을 저장한다면 블럭을 만들기 위한 모든 정보를 가지고 있어야 합니다.

어떻게 진행되나요?? @junk-sound @zeroFruit 

"합의를 요청한 임시 블럭"을 가지고 있다면 
```go
type ConsensusFinished struct {
	Seal      []byte
	TxList    []Tx
	TxSeal    [][]byte
	Timestamp time.Time
	Creator   []byte
}
```
정도만 필요할 것 같습니다.

의견 주시면 감사하겠습니다!

**Reference**
.

**Comment by zeroFruit** [comment]
block id인 seal만 보내도 괜찮을 거 같습니다.
