### ISSUE TITLE
[consensus] 패키지 변경에 따른 README.md 업데이트

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#685]
**Component**
consensus - pbft (doc)

**Assignee**
 consensus를 이해하면서 첫 commit하기에 좋을 것 같습니다!

**Problem or Necessity**
기존 `/it-chain/engine/consensus` 에서 `/it-chain/engine/consensus/pbft` 로 패키지가 변경되면서 `.../pbft/README.md`가 업데이트 되어야합니다.

**Detail**
`/it-chain/engine/consensus`에 README.md를 만들어서 PBFT가 아닌 consensus 자체만을 설명하는 짧은 글이 있으면 좋을 것 같습니다.
더불어 `/it-chain/engine/consensus/pbft/README.nd`에는 PBFT를 설명하는 글만 있으면 좋겠습니다!

그리고 `/it-chain/engine/consensus/pbft/README.nd`에 이미지가 패키지 변경으로 상대경로가 바뀌어 표시 안되는 버그가 있는데 수정이 필요합니다!

**Reference**
.

**Comment by hoonkii** [comment]
넵 작업하겠습니다.
