### ISSUE TITLE
[consensus] consensus msg 네이밍

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#706]
**Componet**
consensus - pbft

**Assignee**
@ChaeByunghoon 

**Proposal Detail**
현재 consensus에 사용되는 consensus msg는 pre-prepare/prepare/commit 메시지가 있습니다.
pre-prepare msg와 prepare msg가 혼동될 우려가 꽤 보여서 이를 propose/prevote/precommit 으로 변경하는 것은 어떨까요?!
실제로 이는 [tendermint](https://github.com/tendermint/tendermint)에서 사용되고 있는 네이밍입니다~

**Reference**
https://github.com/tendermint/tendermint/blob/master/docs/spec/consensus/consensus.md

**Comment by hoonkii** [comment]
네 좋습니다. 의미를 더 잘표현하며, 혼동될 염려도 적어질것 같습니다.
