### ISSUE TITLE
[consensus] StateRepository 버그 리포팅

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#710]
**Componet**
consensus -pbft
(이외에 다른 컴포넌트도 메모리 기반의 repository라면 발생할 수 있습니다.)

**Assignee**
@ChaeByunghoon 
@junbeomlee @junk-sound @zeroFruit @frontalnh @hea9549 

**Bug detail**
file i/o가 아닌 memory 기반의 repo를 사용할 때 문제가 발생할 수 있습니다.

repo에 A를 저장하고 서비스 B와 C가 이 repo를 가지고 있을 때, 포인터를 사용하지 않으면 B가 repo의 A를 조작하여 A'로 바꾸었을 경우 C의 repo에는 A'가 아닌 A가 그대로 남아있는 버그가 생길 수 있습니다!

예를 들어, consensus pbft의 state repository 경우

```go
func NewStateRepository() StateRepository {
	return StateRepository{
		state:   nil,
		RWMutex: sync.RWMutex{},
	}
}

type ExService struct {
	repo StateRepository
}
```
가 아닌
```go
func NewStateRepository() *StateRepository {
	return &StateRepository{
		state:   nil,
		RWMutex: sync.RWMutex{},
	}
}

type ExService struct {
	repo *StateRepository
}
```
와 같은 형식으로 사용해야 합니다.

repository를 여러 서비스에서 동시에 사용할 경우 이런 문제가 발생할 수 있기 때문에 repo 사용에 주의가 필요합니다.

이외의 다른 방법이 있다면 알려주시면 감사하겠습니다!

**Fix plan**
Repository를 포인터로 넘겨주는 식으로 수정해야 합니다.

**Reference**
.

**Comment by hea9549** [comment]
newRepository부분에서는 포인터로 굳이 Repository를 사용안해도될듯합니다!
다만 이 newRepository를 한 뒤 서비스,api에 주입해주기위해 파라미터로 받을때
```go
func newExampleService(repo StateRepository){
~~~~
}
```
와 같이 받으면stateRepository가 클론됩니다.

```go
func newExampleService(repo *StateRepository){
~~~~
}
```
와 같이 파라미터로 주입시켜줄때 포인터를 주의해주면 될 듯합니다
