### ISSUE TITLE
[blockchain] infra/adapter/consensus_finished_event_handler

### ISSUE THREAD

**Issue by zeroFruit** [DE-labtory/it-chain#722]
consensus가 완료되었다는 이벤트를 받는 부분이 필요합니다. consensus 상태에 따라서 블록을 저장하고, sync상태에 따라서 stage하거나 commit 합니다

* eng
in blockchain component, need event handler that receive events which indicate consensus complete.
According to consensus state (event have consensus state), sync state, blockchain component should stage or commit block

**Comment by frontalnh** [comment]
i'll do it!
