### ISSUE TITLE
[consensus] pbft 합의 메시지 네이밍 변경

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#726]
**Component**
consensus - pbft

**Assignee**
.

**Problem or Necessity**
현재 pbft 합의 메시지 네이밍이 혼동될 우려가 있기 때문에 네이밍 변경이 필요합니다!

**Detail**
state.go에서 

```go
type PrePrepareMsg struct {
	StateID        StateID
	SenderID       string
	Representative []*Representative
	ProposedBlock  ProposedBlock
}

type PrepareMsg struct {
	StateID   StateID
	SenderID  string
	BlockHash []byte
}

type CommitMsg struct {
	StateID  StateID
	SenderID string
}
```
의 네이밍을 tendermint 에서 사용하는 이름인 `propose / prevote / precommit`으로 변경되어야 합니다.

**Reference**
#706 
https://github.com/tendermint/tendermint/blob/master/docs/spec/consensus/consensus.md

**Comment by JLGGG** [comment]
작업하겠습니다.
