### ISSUE TITLE
[consensus] state api의 repository 수정

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#727]
**Componet**
consensus - pbft

**Assignee**
.

**Bug detail**
#710 과 관련하여 api 가 수정되어야 합니다.

**Fix plan**
StateApi는 repository를 포인터로 가지고 있어야 합니다.
그리고 #710 이슈를 검증할 수 있는 테스트 케이스도 추가되면 좋을 것 같습니다!

**Reference**
.

**Comment by hoonkii** [comment]
진행하겠습니다.
