### ISSUE TITLE
[p2p] avengers 활용하여 election_service 가상 환경 테스트케이스 작성하기

### ISSUE THREAD

**Issue by frontalnh** [DE-labtory/it-chain#728]
**Component**
p2p 컴포넌트

**Detail**
p2p 컴포넌트의 election_service 에 avengers 를 활용하여 가상환경 기반의 테스트케이스를 작성하기

테스트 케이스 완료 함수 목록
- [x] TestElectionService_Vote
- [x] TestElectionService_RequestVote
- [x] TestElectionService_DecideToBeLeader <= @zeroFruit
- [x] TestElectionService_BroadcastLeader 
- [x] TestElectionService_ElectLeaderWithRaft
- [x] TestNewElectionService <= @zeroFruit
- [x] TestGenRandomInRange

**Reference**
https://github.com/it-chain/avengers

**Comment by frontalnh** [comment]
현재 elect leader with raft 함수는 작성중에 있습니다

**Comment by zeroFruit** [comment]
@frontalnh 혹시 남은 부분 있나요? 

> p2p 컴포넌트의 election_service 에 avengers 를 활용하여 가상환경 기반의 테스트케이스를 작성하기
 
p2p 전체 테스트케이스가 대상인가요??

**Comment by frontalnh** [comment]
@zeroFruit 많이 남아있습니다 현재 되어있는 부분과 electwithraft 함수테스트를 제외하고 모두 작성을 필요로 합니다.
elec with raft는 오늘 중으로 구현이 완료됩니다!

**Comment by zeroFruit** [comment]
@frontalnh BroadcastLeader 해보겠습니다. 지금 풀리퀘에 변경된 코드가 조금 있는 거 같은데 그거 반영해서 테스트 짜볼게요

**Comment by frontalnh** [comment]
@zeroFruit  넵 ㅎㅎ 추가적으로 로그의 failed to consume의 경우 고루틴이 모든 테스트 이후 올바르게 종료되는지를 파악하기 위한 로그로써 잘못된 것이 아니니 참고부탁드립니다.

**Comment by frontalnh** [comment]
elect leader with laft 구현 완료되었습니다

**Comment by zeroFruit** [comment]
BroadcastLeader #751 올라갔습니다

**Comment by zeroFruit** [comment]
DecideToBeLeader, NewElectionService

**Comment by zeroFruit** [comment]
테스트케이스 모두 완료되었습니다
