### ISSUE TITLE
[Main] Delete tmp, db, api-db folder when start engine

### ISSUE THREAD

**Issue by junbeomlee** [DE-labtory/it-chain#756]
**Component**
it-chain.go

**Problem or Necessity**

**Korean**
it-chain은 재 시작시 기존 db를 유지하지 않기 때문에 종료시에 모든 db와 관련된 파일들을 지우고 있습니다. 
```
       func() {
		CommittedBlockRepo.Close()
		os.RemoveAll("./api-db")
	}
```
등등

it-chain은 재 시작시 기존 db를 유지하지 않기 때문에 종료시에 모든 db와 관련된 파일들을 지우고 있습니다. 
하지만 프로그램이 ctrl+z로 stop되면 db관련된 파일들이 지워지지 않습니다.(ctrl+c 로 종료 될경우 signal을 catch해서 처리하고 있습니다) 그래서 시작시점에 db파일들을 지우는 로직을 추가하려고 합니다.

**English**
The it-chain does not maintain the existing db at restart, so it deletes all db-related files at shutdown.
```
       func() {
		CommittedBlockRepo.Close()
		os.RemoveAll("./api-db")
	}
```
However, when the program is stopped with ctrl + z, db related files are not cleared (if ctrl + c has occurred, the signal is caught and engine deletes all db-related files). So I want to add logic to delete db files at the start.

**Comment by junngo** [comment]
진행하겠습니다.
