### ISSUE TITLE
[common] rpc refactoring

### ISSUE THREAD

**Issue by junbeomlee** [DE-labtory/it-chain#761]
**Component**
common

**Assignee**
@junbeomlee

**Problem or Necessity**
rpc에서 현재 return 의 갯수가 2개로 고정되어있고, 자유롭게 구조체를 사용 가능하도록 구현되어있습니다. 
자유로운 구조체에서 -> 지정된 구조체로 하고 callback을 받으면 json.Unmarshal하는 형태로 수정

**Comment by zeroFruit** [comment]
이 부분 지금 진행중인가요?

**Comment by junbeomlee** [comment]
진행 아직 안됬습니다!
