### ISSUE TITLE
[consensus] service의 PropagateService와 adapter PropagateService 구현체의 함수 불일치

### ISSUE THREAD

**Issue by hoonkii** [DE-labtory/it-chain#763]
**Component**
Consensus

**Assignee**
@hihiboss 

**Detail**
service에서 interface로 정의한 PropagateService의 함수들과, adapter의 구현체의 함수들의 리턴타입이 불일치합니다. adapter의 함수 파라미터를 수정해야합니다.

**Reference**
write here

**Comment by ChaeByunghoon** [comment]
진행중
