### ISSUE TITLE
[consensus] PropagateService 인터페이스 수정

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#769]
**Componet**
consensus - pbft

**Assignee**
.

**Bug detail**
Service.go 에 정의된 PropagateService 의 인터페이스가 잘못 정의되어 있습니다.

**Fix plan**
```go
type PropagateService interface {
	BroadcastPrePrepareMsg(msg PrePrepareMsg) error
	BroadcastPrepareMsg(msg PrepareMsg) error
	BroadcastCommitMsg(msg CommitMsg) error
}
```
를
```go
type PropagateService interface {
	BroadcastPrePrepareMsg(msg PrePrepareMsg, representatives []*Representative) error
	BroadcastPrepareMsg(msg PrepareMsg, representatives []*Representative) error
	BroadcastCommitMsg(msg CommitMsg, representatives []*Representative) error
}
```
로 수정해야 합니다.

그리고 이 변경에 따른 테스트 케이스도 수정해야 합니다!

**Reference**
.

**Comment by ghost** [comment]
이거 state_api.go도 같이 수정하는거 맞나요?
state_api.go 파일내의 StartConsensus, HandlePrePrepareMsg, HandlePrepareMsg <-- 이 함수들에도 인자로 representatives가 들어가야할 것같은데... 제가 proposed block에는 representatives가 없겠죠!?

**Comment by hihiboss** [comment]
state_api 는 수정되지 않아도 됩니다!!
api는 state를 가지고 있고, state 내에 representative가 있기 때문에 이 부분은 변경되지 않아도 됩니다~
proposed block은 오직 합의할 블럭의 내용만 가지고 있기 때문에 여기에도 representative는 없어도 될 것 같습니다~

**Comment by ghost** [comment]
@hihiboss  

![image](https://user-images.githubusercontent.com/32866399/45156309-c3e00d80-b218-11e8-8e36-f82dee916c32.png)

현재 sync 맞춰서 service.go 수정 후 
state_api.go에 보면.. 

![image](https://user-images.githubusercontent.com/32866399/45156359-ed993480-b218-11e8-9c6a-3b64cb601afa.png)

위와 같은 에러가 3개가 발생합니다..!

이 에러들은 그냥 무시하고 푸시하면 될까요?

**Comment by hihiboss** [comment]
@owljoa 아아, 그 부분은 수정해주셔야합니당!!
cApi의 repo에서 Load() 함수로 state를 꺼낸 후, 꺼낸 state에서 representative를 가져와 BradcaseProposeMsg에 넣어주면 될 것 같습니다!

풀리퀘 올려주신 코드 보면
```go
func (cApi *StateApiImpl) StartConsensus(proposedBlock pbft.ProposedBlock, representatives []*pbft.Representative) error
func (cApi *StateApiImpl) HandlePrePrepareMsg(msg pbft.PrePrepareMsg, representatives []*pbft.Representative) error 
func (cApi *StateApiImpl) HandlePrepareMsg(msg pbft.PrepareMsg, representatives []*pbft.Representative) error
```
와 같이 api 메소드의 파라미터까지 변경되었는데 이부분이 수정되지 않아도 된다는 뜻이었습니다!!
propagate service의 변경에 따른 api 내 함수의 구현 부분은 수정되어야 합니다~

**Comment by ghost** [comment]
@hihiboss 
아아 넵!!
그런데 
StartConsensus의 경우 

```go
createdState, err := pbft.NewState(peerList, proposedBlock)
```

처럼 createdState가 있고 다른 경우들도 각각 builtState, loadedState가 있는데 이 state들 내에 있는 representatives를 사용해도 될까요??

**Comment by ghost** [comment]
@hihiboss 
아하! 그렇군요. 
메소드 파라미터 변경 없이 state 이용해서 다시 올리겠습니다..!

**Comment by hihiboss** [comment]
@owljoa 네네 그러면 됩니다!!
