### ISSUE TITLE
[it-chain] windows support

### ISSUE THREAD

**Issue by zeroFruit** [DE-labtory/it-chain#770]
windows에서 ivm이 제대로 동작하지 않는 버그가 있었습니다.
ivm에서 사용하고 있는 tesseract 라이브러리에서 관련 버그를 잡아서 현재 작업 중입니다.
(windows 화이팅!)

---

ivm does not work on windows
reason is in tesseract lib which is used by ivm.
fixing is on progress

+edit

From Docker official doc 
> The current version of Docker for Windows runs on 64bit Windows 10 Pro, Enterprise and Education (1607 Anniversary Update, Build 14393 or later).
https://docs.docker.com/docker-for-windows/install/

Currently it-chain-Engine does not support windows which version under 10 Pro where runs docker on toolbox

**Comment by sinramyeon** [comment]
ㅠㅠ win 에서 docker 이슈도 여전합니다(win docker가 안됨)

**Comment by junbeomlee** [comment]
아예 window에서 docker가 안되나요?!1

**Comment by sinramyeon** [comment]
제가요새 집을못들어가서 win기반 빌드를 못해보고 있네요... win으로 다시 확인해보겠습니다. docker 실행시 docker-compose up -d로 실행시 오류가 있었습니다.

**Comment by junbeomlee** [comment]
docker파일이 아직 완성되어있지 않아서 이슈올려놓겠습니다!!
