### ISSUE TITLE
[ivm] deploy with no ssh key

### ISSUE THREAD

**Issue by junbeomlee** [DE-labtory/it-chain#777]
**Component**
ivm, cmd

**Detail**
`it-chain ivm deploy [path] [ssh] [password]` 에서 path만 있을 경우 public한 git repository도 clone 할 수 있도록 기능추가

`it-chain ivm deploy [path] [ssh] [password]`
If deploy command only have [path] value, vim can clone the public git repository

**Comment by junngo** [comment]
진행하겠습니다.
