### ISSUE TITLE
[consensus] Modify 'ConsensusFinished' Event

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#808]
**Component**
consensus - pbft

**Assignee**
.

**Problem or Necessity**
Now, event.go in common is
```go
type ConsensusFinished struct {
	Seal      []byte
	PrevSeal  []byte
	Height    uint64
	TxList    []Tx
	TxSeal    [][]byte
	Timestamp time.Time
	Creator   string
	State     string
}
```
but, this event may have only a Seal.
So, we need your help!

현재 common의 event.go를 보면
```go
type ConsensusFinished struct {
	Seal      []byte
	PrevSeal  []byte
	Height    uint64
	TxList    []Tx
	TxSeal    [][]byte
	Timestamp time.Time
	Creator   string
	State     string
}
```
가 정의되어 있는데 이 event는 Seal만 가지고 있어도 괜찮아 수정이 필요합니다!

**Detail**
Modify 'ConsensusFinished' in event.go and 'HandlePreCommitMsg' in state_api.go.

event.go의 ConsensusFinished와 state_api.go의 HandlePreCommitMsg를 수정해야 합니다.

**Reference**
#675

**Comment by sinramyeon** [comment]
```

func (cApi *StateApiImpl) HandlePreCommitMsg(msg pbft.PreCommitMsg) error {

	loadedState, err := cApi.repo.Load()
	if err != nil {
		return err
	}

	if err := loadedState.SavePreCommitMsg(&msg); err != nil {
		return err
	}

	if !loadedState.CheckPreCommitCondition() {
		return nil
	}

	//TODO ConsensusFinished 인자 추가
	if err := cApi.eventService.Publish("block.confirm", event.ConsensusFinished{}); err != nil {
		return err
	}
	cApi.repo.Remove()

	return nil
}
```

`if err := cApi.eventService.Publish("block.confirm", event.ConsensusFinished{}); err != nil {
		return err` 에서 Seal 값으로 뭘 넘겨줘야 하나요??

또 테스트 코드인 consensus_event_handler_test.go도

```
func TestConsensusEventHandler_HandleConsensusFinishedEvent(t *testing.T) {

	event1 := event2.ConsensusFinished{
		Seal: []byte{},
	}

	event2 := event2.ConsensusFinished{
		Seal: []byte{},
	}
```

아래와 같이 수정하겠습니다

**Comment by hihiboss** [comment]
repo에 저장된 state는 ProposedBlock을 가지고 있습니다!
여기에 있는 seal 값을 넣어주면 됩니다!

그리고 제가 이슈에 빠트리고 적었는데ㅜㅜ event는 seal 외에 byte로 변환된 블럭도 가지고 있어야합니다!
즉, ConsensusFinished 이벤트는
```go
type struct ConsensusFinished {
	Seal 	[]byte
	Body 	[]byte
}
```
일 것 같네요!

Consensus 컴포넌트에선 todo 부분과 common에 있는 event.go의 ConsensusFinished struct만 변경될 것 같고, Blockchain 컴포넌트에선 consensus_event_handler.go의 extractBlockFromEvent 함수가 수정될 것 같네요 :)
