### ISSUE TITLE
[Blockchain] 파일 폴더 변경

### ISSUE THREAD

**Issue by ttkmw** [DE-labtory/it-chain#809]
**Component**
Blockchain

**Assignee**

**Problem or Necessity**
파일 폴더 변경

**Detail**
block_pool.go 위치가 mem에 위치
block_repository.go 는 repo 폴더 만들어서 옮기기

**Reference**
write here

**Comment by JoosJuliet** [comment]
작업해보고 싶은데 혹시 질문이 있으면 slack에서 어떤분께 연락을 드려야 하나요 ???

**Comment by ttkmw** [comment]
@JoosJuliet 저한테 주시면 됩니다 slack에 임근원입니다~

작업은 
1. blockchain/infra 에 "repo" 폴더 생성
2. 현재 blockchain/infra/mem 에 있는 3개의 파일을 repo 폴더로 이동
3. blockchain/block_pool.go 를 blockchain/infra/mem으로 이동
4. 폴더 변경으로인해 혹시 있을 다른 파일에의 영향 확인(아마 없을 것 같아요)

대로 하시면 됩니다.
pool이 메모리에 있어야 하고,
repository는 메모리가 아니라 repo쪽에 위치 시키려고 한 겁니다!
