### ISSUE TITLE
[main] golang dependency injection

### ISSUE THREAD

**Issue by junbeomlee** [DE-labtory/it-chain#815]
**Componet**
main

**Proposal Detail**
How about using dependency injection library?
ref: https://blog.drewolson.org/dependency-injection-in-go

**Comment by sinramyeon** [comment]
If you are used to web development, You can check about DI in golang by iris framework(https://github.com/kataras/iris). this package called hero(https://github.com/kataras/iris/blob/master/hero) contains Di example. If we gonna use DI library, we should concern about DI pattern also comes with the cost of increased complexity during initialization.
