### ISSUE TITLE
[common] common/logger to library

### ISSUE THREAD

**Issue by junbeomlee** [DE-labtory/it-chain#823]
**Componet**
common/logger

**Proposal Detail**
Make common/logger a library and modify engine, bifrost, tesseract to use the corresponding library

**Comment by junngo** [comment]
진행하겠습니다.

**Comment by junbeomlee** [comment]
@junngo 라이브러리는 완성되었나요?!!

**Comment by junngo** [comment]
@junbeomlee 네!! 분리는 하였으며 추가내용이 있으면 수정을 하도록 하겠습니다. engine은 로그 수정 중이며 PR하도록 하겠습니다 :)
