### ISSUE TITLE
[consensus] CreateGrpcDeliverCommand 통합하기

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#850]
**Component**
consensus - pbft

**Assignee**
.

**Problem or Necessity**
In the Consensus component, this function is used repeatedly.

consensus 내에서 해당 함수가 패키지마다 중복 구현되어 사용되고 있습니다.

**Detail**
How about moving CreateGrpcDeliverCommand function to util in common package.

CreateGrpcDeliverCommand 함수를 common의 util로 옮겨서 사용하는게 어떨까요?!

**Reference**
.

**Comment by sinramyeon** [comment]
util.go로

```
func createGrpcDeliverCommand(protocol string, body interface{}) (command.DeliverGrpc, error) {

	data, err := common.Serialize(body)

	if err != nil {
		return command.DeliverGrpc{}, err
	}

	return command.DeliverGrpc{
		MessageId:     xid.New().String(),
		RecipientList: make([]string, 0),
		Body:          data,
		Protocol:      protocol,
	}, err
}
```

이동 하겠습니다
