### ISSUE TITLE
[consensus] Modify TestGenRandomInRange in election_api_test.go

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#851]
**Component**
consensus - pbft

**Assignee**
.

**Detail**
In test functions, there is a function which tests that the value corresponds to a correct range. So, please modify this test case to use that function!

테스트 함수 중, 범위에 해당하는 값인지 테스트하는 함수가 있는데 이를 사용하도록 테스트를 수정해주세요!

**Reference**
.

**Comment by sinramyeon** [comment]
```

func TestGenRandomInRange(t *testing.T) {
	v1 := pbft.GenRandomInRange(0, 10)
	v2 := pbft.GenRandomInRange(0, 10)
	v3 := pbft.GenRandomInRange(0, 10)

	t.Logf("%v", v1)
	t.Logf("%v", v2)
	t.Logf("%v", v3)
}
```

이걸 어떤 함수로 바꾼다는 뜻인가요??

**Comment by hihiboss** [comment]
@hero0926 
지금 테스트케이스에서는 단순히 랜덤값을 log로 찍어서 확인하고 있는데, 이를 assert 를 이용하여 테스트해야 합니다!
go doc을 찾아보니 따로 range를 검사하는 함수는 없는 것 같습니다...ㅜ

assert에 `func Contains(t TestingT, s, contains interface{}, msgAndArgs ...interface{}) bool` 함수가 존재하는데 이를 이용하면 테스트할 수 있을것 같습니다!
