### ISSUE TITLE
[consensus] Move state repository to infra/mem

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#857]
**Component**
consensus - pbft

**Assignee**
@hihiboss

**Problem or Necessity**
Repository in infra/mem is more suitable than in domain.

**Detail**
Move state repository to infra/mem from domain

**Reference**
.

**Comment by hoonkii** [comment]
이 경우 domain 에서는 Repository의 Interface가 있고 infra/mem/ 에 Repository의 구현체가 오는건가요??

**Comment by hihiboss** [comment]
@ChaeByunghoon 
네 그렇습니다!
