### ISSUE TITLE
[blockchain] remove HandleProposeBlockCommand rpc.Error

### ISSUE THREAD

**Issue by zeroFruit** [DE-labtory/it-chain#883]
instead of return rpc.Error just return err. We don't use rpc anymore

**Comment by zeroFruit** [comment]
@zeroFruit

**Comment by sinramyeon** [comment]
아직 여기저기 rpc.Error가 쓰이는데 상기 메서드에서만 삭제하나요??

**Comment by zeroFruit** [comment]
이 부분은 it-chain/cmd/on 에서 다 와이어링 되어있어서 날 잡고 한번에 다 지워야할 거 같아요!
