### ISSUE TITLE
[ connections ] 자기자신에게 연결시fatal

### ISSUE THREAD

**Issue by hea9549** [DE-labtory/it-chain#903]
자기자신에게 join시 (또는 이미 있는 연결에 join시)
fatal후 프로그램이 종료됨.

에러리턴 후 로그하는게 나을듯함.

**Comment by sinramyeon** [comment]
어디쪽 connection 인가요??

**Comment by hea9549** [comment]
api-gateway 에서만 발생했던듯 합니다. 제가 실수로 fatal처리하게해서...

수정했습니다.!
