### ISSUE TITLE
[consensus] Refactory making receipients from representative

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#944]
**Component**
consensus - pbft

**Assignee**
.

**Detail**
In state_api.go,
```go
receipients := make([]pbft.Representative, 0)
for _, rep := range state.Representatives {
	if rep.ID != s.publisherID {
		receipients = append(receipients, rep)
	}
}
```
is duplicated. So, it will be good that you separate this to 'state' domain function.

state_api.go에서
```go
receipients := make([]pbft.Representative, 0)
for _, rep := range state.Representatives {
	if rep.ID != s.publisherID {
		receipients = append(receipients, rep)
	}
}
```
가 중복되고 있는데 이를 state 도메인 함수로 따로 빼면 좋을 것 같습니다!

**Reference**
.

**Comment by xodhx4** [comment]
작업해보고 싶습니다! 어떤 분께 연락드려야 할까요?

**Comment by hihiboss** [comment]
작업중 댓글 다시고 작업하시면 됩니다!!
그리고 질문있으시면 저(@hihiboss)에게 질문주세요!!

**Comment by xodhx4** [comment]
작업중입니다!
