### ISSUE TITLE
[common] cannot find package "github.com/it-chain/heimdall/key"

### ISSUE THREAD

**Issue by xodhx4** [DE-labtory/it-chain#952]
**Componet**
common - id

**Assignee**
.

**Bug detail**
윈도우에서 go test 시 
```sh
common\id.go:23:2: cannot find package "github.com/it-chain/heimdall/key" in any of:
        C:\Go\src\github.com\it-chain\heimdall\key (from $GOROOT)
        C:\Users\kimta\go\src\github.com\it-chain\heimdall\key (from $GOPATH)
```
오류가 존재합니다.
실제 저 위치에서 "github.com/it-chain/heimdall/key"를 import하고 있지만 
헤임달 프로젝트에서는 key.go는 있지만 key라는 package는 존재하지 않고 있습니다.
혹 제가 뭔가 잘못 테스트 한 것인지 오류인지 모르겠습니다.

**Comment by junbeomlee** [comment]
우선 src/github.com/it-chain폴더 안에서 혹시 engine말고 다른 폴더가있다면 모두 지워주시고 engine폴더안에서 dep ensure 한번 해주세요!!
dep ensure -update는 하시면 안됩니다!!

**Comment by xodhx4** [comment]
감사합니다 작동하네요!
