### ISSUE TITLE
[PBFT] state api test case

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#957]
**Component**
consensus - pbft

**Assignee**
anyone

**Detail**
Implement test cases for state api.
(`func TestNewStateApi`, `func TestStateApi_StartConsensus`, `func TestStateApi_AcceptProposal`, `func TestStateApi_ReceivePrevote`, `func TestStateApi_ReceivePreCommit`)

**Reference**
.

**Comment by zeroFruit** [comment]
avengers 테스트인가요?

**Comment by hihiboss** [comment]
유닛 테스트와 avengers 테스트 모두 진행되어야 합니다!!
