### ISSUE TITLE
[PBFT] refactor to new function in temp msg pool

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#958]
**Component**
consensus - pbft

**Assignee**
anyone

**Detail**
In state api, a logic which gets temp msg pool items, saves them to state's msg pool and removes all msg in temp msg pool is duplicated. So, refactor this logic to new function.

```go
// todo : refact to new function (UpdateMsgPool)
	for _, poolMsg := range s.tempPrevoteMsgPool.Get() {
		if err := loadedState.PrevoteMsgPool.Save(&poolMsg); err != nil {
			iLogger.Errorf(nil, "[PBFT] Saving prevote msg is failed - Error: [%s]")
		}
	}
	s.tempPrevoteMsgPool.RemoveAllMsgs()
```

**Reference**
.

**Comment by zeroFruit** [comment]
@zeroFruit 코드 공부할겸 진행하겠습니다
