### ISSUE TITLE
[Doc] architecture documentation update

### ISSUE THREAD

**Issue by sinramyeon** [DE-labtory/it-chain#962]
Componet
Doc

Assignee
All contributor

Proposal Detail
Update Architecture.md file based on the it-chain archiecture documentation from 4.(Korean, English)

1,2,3꼭지는 제가 한글버전을 업데이트해서 4부분을 해주시거나(김) 혹은 1, 2, 3, 4, 영문판 번역을 해 주시면 될 것 같습니다.

**Comment by xodhx4** [comment]
@hero0926 
한글 4부분을 하려고 하는데, 문제는 code 부분이 이미지로 되어있습니다! Text로 삽입할 수 있게 text를 가지고 계신 분이 있으신가요? 아니면 그냥 이미지로 넣어야 하나요?

**Comment by junbeomlee** [comment]
안녕하세요 code부분은 아마 cli부분인것 같은데 cli는 이미 doc으로 되어있어서 안하셔도 됩니다!!

**Comment by junbeomlee** [comment]
영어 버전은 제가 하겠습니다!

**Comment by junbeomlee** [comment]
영어 버전 chapter 4 남았습니다!!
