### ISSUE TITLE
[SmartContract] bank icode

### ISSUE THREAD

**Issue by junbeomlee** [DE-labtory/it-chain#963]
**Component**
ICode

**Detail**
Implement a bank smartcontract(ex bitcoin)

**Comment by nesticat** [comment]
저 해보고 싶습니다!

**Comment by junbeomlee** [comment]
learn-icode와 sdk를 한번 보시고, learn-icode처럼 스마트컨트랙 작성해주시면 됩니다!
bank는 invoke operation으로 mint와 transfer 기능이 필요할 것 같고 query는 계정조회, 계정의 balance조회 정도가 필요할 것 같습니다! 추가적으로 궁금한 사항 있으시면 알려주세요!

**Comment by nesticat** [comment]
넵 일과중엔 힘들듯 하고 저녁에 시간내서 진행해보겠습니다!
