### ISSUE TITLE
[PBFT] CreateDeliverGrpcCommand in propagate service

### ISSUE THREAD

**Issue by hihiboss** [DE-labtory/it-chain#974]
**Component**
consensus - pbft

**Assignee**
.

**Detail**
propagate service에 createDeliverGrpcCommand가 정의되어 사용되고 있는데, 이를 제거하고 Common 패키지의 CreateDeliverGrpcCommand 함수로 사용해야 합니다.

**Reference**
#850

**Comment by sinramyeon** [comment]
제가 util.go에 만든게 CreateGrpcDeliverCommand 입니다. 수정했습니다.
